/**
 * Global Style Sheet — LIV Golf Premium Dark Design System
 *
 * Color semantics:
 *   bg / surface1 / surface2 / surface3   — background hierarchy (dark → darker)
 *   gold / goldLight / goldBg             — primary accent
 *   greenAccent / greenBg                 — secondary accent (golf heritage)
 *   textPrimary / textSecondary / textMuted — type hierarchy
 *   border / borderMid / borderGold       — outline hierarchy
 *
 * All key names preserved from original — only values changed.
 */

// ─── Design Tokens (inline for zero-import overhead) ────────────────────────
const C = {
  bg:           '#0b0e18',
  surface1:     '#111827',
  surface2:     '#1a2235',
  surface3:     '#212a40',
  hero:         '#0e1c14',
  heroBorder:   '#1a3028',
  heroText:     '#3db87a',
  heroTextDim:  '#2a6048',

  gold:         '#c9a228',
  goldLight:    '#e8c84e',
  goldMuted:    '#7a611a',
  goldBg:       'rgba(201,162,40,0.10)',
  goldBgStrong: 'rgba(201,162,40,0.18)',

  greenAccent:  '#3db87a',
  greenBg:      'rgba(61,184,122,0.10)',

  textPrimary:  '#e8edf8',
  textSec:      '#8896b0',
  textMuted:    '#4d5a78',
  textInverse:  '#0b0e18',

  border:       '#1b2238',
  borderMid:    '#252f4a',
  borderGold:   '#c9a228',

  birdie:       '#3db87a',
  eagle:        '#c9a228',
  eagleLight:   '#e8c84e',
  par:          '#8896b0',
  bogey:        '#6b7c9a',
  double_:      '#ef5350',
  triple:       '#c62828',

  error:        '#ef5350',
  errorBg:      'rgba(239,83,80,0.12)',
  success:      '#3db87a',
  successBg:    'rgba(61,184,122,0.10)',
  warning:      '#c9a228',
  warningBg:    'rgba(201,162,40,0.10)',

  white:        '#ffffff',
  scrim:        'rgba(11,14,24,0.88)',
};

const F = "'Noto Sans KR', -apple-system, 'Helvetica Neue', sans-serif";

const styles = {
  // ─── App Shell ──────────────────────────────────────────────────────────
  app: {
    minHeight: '100vh',
    background: C.bg,
    fontFamily: F,
    color: C.textPrimary,
    paddingBottom: '0',
    width: '100%',
    overflowX: 'hidden',
  },
  container: {
    width: '100%',
    maxWidth: '520px',
    margin: '0 auto',
    padding: '20px 16px 100px',
    animation: 'fadeIn 0.3s ease-out',
    boxSizing: 'border-box',
  },
  header: {
    padding: '16px 0 28px',
  },
  headerTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  userSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  actionButton: {
    background: 'none',
    border: 'none',
    padding: '4px 6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: C.textSec,
    cursor: 'pointer',
    transition: 'color 0.2s ease',
  },
  userName: {
    fontSize: '13px',
    fontWeight: '700',
    color: C.gold,
  },
  logoutButton: {
    background: 'none',
    border: 'none',
    padding: '4px 8px',
    display: 'flex',
    alignItems: 'center',
    color: C.textSec,
    cursor: 'pointer',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  logoMark: {
    fontSize: '26px',
  },
  brandName: {
    fontFamily: F,
    fontSize: '20px',
    fontWeight: '800',
    letterSpacing: '0.05em',
    color: C.textPrimary,
    lineHeight: 1,
  },
  brandTagline: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: C.gold,
    textTransform: 'uppercase',
    marginTop: '3px',
    fontWeight: '700',
  },
  dateLine: {
    fontSize: '12px',
    color: C.textMuted,
    marginTop: '18px',
    letterSpacing: '0.06em',
  },

  // ─── Login ──────────────────────────────────────────────────────────────
  loginCard: {
    background: C.surface1,
    padding: '44px 28px 36px',
    borderRadius: '4px',
    border: `1px solid ${C.border}`,
    textAlign: 'center',
    marginTop: '48px',
  },
  loginLogo: {
    fontSize: '60px',
    marginBottom: '20px',
  },
  loginTitle: {
    fontSize: '28px',
    fontWeight: '800',
    color: C.textPrimary,
    margin: '0 0 8px',
    letterSpacing: '-0.02em',
  },
  loginSubtitle: {
    fontSize: '14px',
    color: C.textSec,
    margin: '0 0 40px',
  },
  loginForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },

  // ─── Hero Card (home, scoring header panel) ──────────────────────────────
  heroCard: {
    background: `linear-gradient(135deg, ${C.hero} 0%, #0f2218 100%)`,
    color: C.textPrimary,
    padding: '28px 24px',
    borderRadius: '4px',
    marginBottom: '18px',
    position: 'relative',
    overflow: 'hidden',
    textAlign: 'center',
    border: `1px solid ${C.heroBorder}`,
    boxShadow: '0 4px 24px rgba(0,0,0,0.5)',
  },
  heroLabel: {
    fontSize: '10px',
    letterSpacing: '0.3em',
    color: C.gold,
    marginBottom: '14px',
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  heroTitle: {
    fontFamily: F,
    fontSize: '28px',
    fontWeight: '800',
    margin: '0 0 24px',
    lineHeight: 1.3,
    letterSpacing: '-0.02em',
    color: C.textPrimary,
  },
  heroButton: {
    background: C.gold,
    color: C.textInverse,
    padding: '14px 20px',
    borderRadius: '2px',
    fontSize: '13px',
    fontWeight: '700',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
  },

  // ─── Stats Grid ─────────────────────────────────────────────────────────
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
    marginBottom: '24px',
  },
  statCard: {
    background: C.surface1,
    padding: '18px 16px',
    borderRadius: '4px',
    border: `1px solid ${C.border}`,
    textAlign: 'center',
    boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
  },
  statLabel: {
    fontSize: '10px',
    letterSpacing: '0.18em',
    color: C.textSec,
    textTransform: 'uppercase',
    marginBottom: '10px',
    fontWeight: '700',
  },
  statValue: {
    fontFamily: F,
    fontSize: '30px',
    fontWeight: '800',
    color: C.textPrimary,
    lineHeight: 1,
    letterSpacing: '-0.03em',
  },

  // ─── Section ─────────────────────────────────────────────────────────────
  section: {
    marginBottom: '28px',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  sectionTitle: {
    fontSize: '10px',
    letterSpacing: '0.22em',
    color: C.textSec,
    textTransform: 'uppercase',
    fontWeight: '700',
    marginBottom: '12px',
  },
  textLink: {
    background: 'none',
    fontSize: '12px',
    color: C.gold,
    textDecoration: 'none',
    fontWeight: '600',
    letterSpacing: '0.04em',
    border: 'none',
    cursor: 'pointer',
  },

  // ─── Round Row (Home recent rounds) ────────────────────────────────────
  roundRow: {
    background: C.surface1,
    width: '100%',
    padding: '16px 18px',
    borderRadius: '4px',
    border: `1px solid ${C.border}`,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    textAlign: 'left',
    boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
  },
  roundRowLeft: {
    flex: 1,
  },
  roundCourse: {
    fontSize: '15px',
    fontWeight: '700',
    color: C.textPrimary,
    marginBottom: '4px',
  },
  roundDate: {
    fontSize: '12px',
    color: C.textSec,
  },
  dot: { color: C.textMuted },
  roundRowRight: {
    textAlign: 'right',
  },
  roundScore: {
    fontFamily: F,
    fontSize: '26px',
    fontWeight: '800',
    color: C.textPrimary,
    lineHeight: 1,
    letterSpacing: '-0.03em',
  },
  roundDiff: {
    fontSize: '12px',
    fontWeight: '700',
    marginTop: '2px',
  },

  // ─── Nav Grid (Home quick links) ────────────────────────────────────────
  navGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
    marginTop: '8px',
  },
  navCard: {
    background: 'transparent',
    padding: '20px 16px',
    borderRadius: '4px',
    border: `1px solid ${C.borderMid}`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    color: C.textPrimary,
    fontSize: '12px',
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'border-color 0.15s',
  },

  // ─── Page Header ─────────────────────────────────────────────────────────
  pageHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 0 24px',
  },
  pageTitle: {
    fontFamily: F,
    fontSize: '20px',
    fontWeight: '800',
    color: C.textPrimary,
    letterSpacing: '-0.01em',
  },
  iconBack: {
    width: '40px',
    height: '40px',
    background: 'transparent',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: C.textSec,
    cursor: 'pointer',
    border: 'none',
  },

  // ─── Form ────────────────────────────────────────────────────────────────
  formSection: {
    marginBottom: '24px',
  },
  formLabel: {
    display: 'block',
    fontSize: '10px',
    letterSpacing: '0.22em',
    color: C.textSec,
    textTransform: 'uppercase',
    fontWeight: '700',
    marginBottom: '10px',
  },
  formLabelRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  formInput: {
    width: '100%',
    padding: '13px 14px',
    fontSize: '15px',
    border: `1px solid ${C.borderMid}`,
    borderRadius: '4px',
    background: C.surface2,
    color: C.textPrimary,
    outline: 'none',
    marginBottom: '10px',
    fontFamily: F,
  },
  addButton: {
    background: 'transparent',
    color: C.gold,
    fontSize: '12px',
    fontWeight: '700',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    border: 'none',
    cursor: 'pointer',
    letterSpacing: '0.06em',
  },
  playerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  playerBadge: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    background: C.gold,
    color: C.textInverse,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: '700',
    flexShrink: 0,
  },
  removeButton: {
    width: '32px',
    height: '32px',
    background: 'transparent',
    color: C.textMuted,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    border: 'none',
    cursor: 'pointer',
  },

  // ─── Par Setup Table ──────────────────────────────────────────────────────
  parTableHint: {
    fontSize: '11px',
    color: C.textMuted,
    textAlign: 'center',
    marginBottom: '10px',
    fontStyle: 'italic',
  },
  parTable: {
    background: C.surface1,
    border: `1px solid ${C.borderMid}`,
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '10px',
  },
  parTableRow: {
    display: 'flex',
    alignItems: 'stretch',
    borderBottom: `1px solid ${C.border}`,
    minHeight: '36px',
  },
  parTableLabel: {
    width: '54px',
    flexShrink: 0,
    background: C.surface2,
    borderRight: `1px solid ${C.borderMid}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    letterSpacing: '0.1em',
    fontWeight: '700',
    color: C.textSec,
  },
  parTableLabelHeader: {
    background: C.hero,
    color: C.gold,
    fontSize: '11px',
    letterSpacing: '0.1em',
    whiteSpace: 'normal',
    wordBreak: 'break-word',
    lineHeight: '1.25',
    textAlign: 'center',
    padding: '4px 3px',
  },
  parTableCells: {
    display: 'grid',
    gridTemplateColumns: 'repeat(9, 1fr)',
    flex: 1,
    minWidth: 0,
  },
  parTableHoleCell: {
    padding: '6px 0',
    fontSize: '12px',
    fontWeight: '700',
    color: C.textSec,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: `1px solid ${C.border}`,
    minWidth: 0,
  },
  parTableParCell: {
    padding: '4px 2px',
    borderRight: `1px solid ${C.border}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
    position: 'relative',
  },
  parTableParValue: {
    width: '26px',
    height: '26px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: '700',
    lineHeight: 1,
    transition: 'all 0.15s ease',
    pointerEvents: 'none',
    zIndex: 1,
  },
  parTapZone: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '50%',
    background: 'transparent',
    border: 'none',
    padding: 0,
    zIndex: 2,
  },
  parTableTotal: {
    width: '54px',
    flexShrink: 0,
    background: C.surface2,
    borderLeft: `1.5px solid ${C.borderMid}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: '800',
    color: C.textPrimary,
  },
  parTableTotalHeader: {
    background: C.hero,
    color: C.gold,
    fontSize: '10px',
    letterSpacing: '0.15em',
  },
  parLegend: {
    display: 'flex',
    justifyContent: 'space-around',
    gap: '8px',
    padding: '12px 8px',
    background: C.surface2,
    borderRadius: '4px',
    marginTop: '10px',
    flexWrap: 'wrap',
  },
  parLegendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '11px',
    color: C.textSec,
    fontWeight: '600',
  },
  parLegendDot: {
    width: '22px',
    height: '22px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: '700',
  },
  parSummary: {
    background: `linear-gradient(135deg, ${C.hero} 0%, #0f2218 100%)`,
    color: C.textPrimary,
    borderRadius: '4px',
    padding: '18px 20px',
    marginBottom: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
    border: `1px solid ${C.heroBorder}`,
    boxShadow: '0 4px 16px rgba(0,0,0,0.4)',
  },
  parSummaryMain: {
    flex: 1,
    textAlign: 'center',
  },
  parSummaryLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: C.gold,
    fontWeight: '700',
    marginBottom: '4px',
    textTransform: 'uppercase',
  },
  parSummaryValue: {
    fontFamily: F,
    fontSize: '38px',
    fontWeight: '800',
    lineHeight: 1,
    letterSpacing: '-0.02em',
    color: C.textPrimary,
  },
  parSummaryDivider: {
    width: '1px',
    height: '50px',
    background: C.heroBorder,
  },
  parSummaryNines: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: '90px',
  },
  parSummaryNineRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: '12px',
  },
  parSummaryNineLabel: {
    fontSize: '10px',
    letterSpacing: '0.2em',
    color: C.gold,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  parSummaryNineValue: {
    fontFamily: F,
    fontSize: '18px',
    fontWeight: '700',
    color: C.textPrimary,
  },

  // ─── Buttons ─────────────────────────────────────────────────────────────
  primaryButton: {
    width: '100%',
    padding: '16px',
    background: C.gold,
    color: C.textInverse,
    fontSize: '13px',
    fontWeight: '700',
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    borderRadius: '2px',
    marginTop: '12px',
    border: 'none',
    cursor: 'pointer',
    fontFamily: F,
  },
  secondaryButton: {
    flex: 1,
    padding: '14px',
    background: 'transparent',
    border: `1px solid ${C.borderMid}`,
    color: C.textPrimary,
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    borderRadius: '2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    cursor: 'pointer',
    fontFamily: F,
  },
  reportActions: {
    marginTop: '12px',
    marginBottom: '20px',
  },
  reportActionRow: {
    display: 'flex',
    gap: '10px',
    marginTop: '10px',
  },

  // ─── Scoring Header ───────────────────────────────────────────────────────
  scoringHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 0 16px',
  },
  scoringCourse: {
    fontSize: '13px',
    fontWeight: '700',
    color: C.textPrimary,
    letterSpacing: '-0.01em',
    textAlign: 'center',
  },

  // ─── Progress Bar ─────────────────────────────────────────────────────────
  progressBar: {
    marginBottom: '12px',
  },
  progressText: {
    display: 'flex',
    alignItems: 'baseline',
    marginBottom: '6px',
  },
  progressNumber: {
    fontFamily: F,
    fontSize: '18px',
    fontWeight: '800',
    color: C.textPrimary,
    lineHeight: 1,
  },
  progressTotal: {
    fontSize: '11px',
    color: C.textSec,
    letterSpacing: '0.1em',
    marginLeft: '4px',
  },
  progressTrack: {
    height: '3px',
    background: C.surface3,
    borderRadius: '2px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: C.gold,
    borderRadius: '2px',
    transition: 'width 0.3s ease',
  },

  // ─── Running Score Panel ─────────────────────────────────────────────────
  runningScore: {
    background: `linear-gradient(135deg, ${C.hero} 0%, #0f2218 100%)`,
    color: C.textPrimary,
    borderRadius: '4px',
    padding: '14px 16px',
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'stretch',
    gap: '16px',
    border: `1px solid ${C.heroBorder}`,
    boxShadow: '0 4px 16px rgba(0,0,0,0.4)',
  },
  runningScoreMain: {
    flex: '0 0 auto',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: '100px',
  },
  runningScoreLabel: {
    fontSize: '9px',
    letterSpacing: '0.22em',
    color: C.gold,
    fontWeight: '700',
    marginBottom: '6px',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '100px',
    textAlign: 'center',
  },
  runningScoreValues: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: '8px',
  },
  runningScoreNumber: {
    fontFamily: F,
    fontSize: '30px',
    fontWeight: '800',
    lineHeight: 1,
    color: C.textPrimary,
    letterSpacing: '-0.03em',
  },
  runningScoreDiff: {
    fontSize: '14px',
    fontWeight: '700',
    letterSpacing: '0.02em',
  },
  runningScoreDivider: {
    width: '1px',
    background: C.heroBorder,
    flexShrink: 0,
  },
  runningScoreStats: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-around',
    gap: '8px',
  },
  runningScoreStat: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    minWidth: 0,
  },
  runningScoreStatLabel: {
    fontSize: '9px',
    letterSpacing: '0.2em',
    color: C.gold,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  runningScoreStatValue: {
    fontFamily: F,
    fontSize: '18px',
    fontWeight: '800',
    color: C.textPrimary,
    lineHeight: 1,
    letterSpacing: '-0.02em',
  },

  // ─── Hole Navigator ──────────────────────────────────────────────────────
  holeNavigator: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    marginBottom: '4px',
    padding: '6px 0 16px',
  },
  holeNavTable: {
    background: C.surface1,
    border: `1px solid ${C.borderMid}`,
    borderRadius: '4px',
    overflow: 'hidden',
  },
  holeNavTableRow: {
    display: 'flex',
    alignItems: 'stretch',
    borderBottom: `1px solid ${C.border}`,
    minHeight: '30px',
  },
  holeNavRowLabel: {
    width: '48px',
    flexShrink: 0,
    background: C.surface2,
    borderRight: `1px solid ${C.borderMid}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    letterSpacing: '0.12em',
    fontWeight: '700',
    color: C.textSec,
  },
  holeNavRowLabelHeader: {
    background: C.hero,
    color: C.gold,
    fontSize: '11px',
    letterSpacing: '0.15em',
  },
  holeNavTableCells: {
    display: 'grid',
    gridTemplateColumns: 'repeat(9, 1fr)',
    flex: 1,
    minWidth: 0,
  },
  holeNavHoleCell: {
    background: 'transparent',
    border: 'none',
    borderRight: `1px solid ${C.border}`,
    padding: '6px 0',
    fontSize: '13px',
    fontWeight: '700',
    color: C.textPrimary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
    cursor: 'pointer',
  },
  holeNavParCell: {
    borderRight: `1px solid ${C.border}`,
    padding: '5px 0',
    fontSize: '12px',
    fontWeight: '600',
    color: C.textSec,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
  },
  holeNavScoreCell: {
    background: 'transparent',
    border: 'none',
    borderRight: `1px solid ${C.border}`,
    padding: '4px 2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
    cursor: 'pointer',
  },

  // ─── Score Markers ───────────────────────────────────────────────────────
  scoreMarker: {
    width: '26px',
    height: '26px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    lineHeight: 1,
    position: 'relative',
    color: C.textPrimary,
    fontWeight: '700',
  },
  markerBirdie: {
    borderRadius: '50%',
    border: `2px solid ${C.birdie}`,
    color: C.birdie,
  },
  markerEagle: {
    borderRadius: '50%',
    border: `2px solid ${C.eagle}`,
    boxShadow: `0 0 0 2px ${C.surface1}, 0 0 0 3.5px ${C.eagle}`,
    color: C.eagle,
  },
  markerHoleInOne: {
    borderRadius: '50%',
    background: `linear-gradient(135deg, ${C.eagleLight} 0%, ${C.eagle} 50%, ${C.goldMuted} 100%)`,
    backgroundSize: '200% 200%',
    animation: 'holeInOneShine 3s ease-in-out infinite',
    boxShadow: `0 0 0 2px ${C.surface1}, 0 0 0 3.5px ${C.eagle}, 0 2px 8px rgba(201,162,40,0.4)`,
    fontWeight: '800',
    color: C.textInverse,
  },
  holeInOneStar: {
    position: 'absolute',
    top: '-8px',
    right: '-6px',
    fontSize: '10px',
    color: C.eagle,
    textShadow: `0 0 3px ${C.bg}, 0 1px 2px rgba(0,0,0,0.4)`,
    lineHeight: 1,
  },
  markerPar: {
    color: C.par,
  },
  markerBogey: {
    border: `2px solid ${C.bogey}`,
    borderRadius: '2px',
    color: C.bogey,
  },
  markerDouble: {
    border: `2px solid ${C.double_}`,
    borderRadius: '2px',
    boxShadow: `0 0 0 2px ${C.surface1}, 0 0 0 3.5px ${C.double_}`,
    color: C.double_,
  },

  // ─── Hole Header ─────────────────────────────────────────────────────────
  holeHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '24px 0 20px',
    borderTop: `1px solid ${C.border}`,
    borderBottom: `1px solid ${C.border}`,
    marginBottom: '24px',
  },
  holeLabel: {
    fontSize: '11px',
    letterSpacing: '0.25em',
    color: C.gold,
    fontWeight: '700',
    marginBottom: '4px',
    textTransform: 'uppercase',
  },
  holePar: {
    fontFamily: F,
    fontSize: '30px',
    fontWeight: '800',
    color: C.textPrimary,
    lineHeight: 1,
    letterSpacing: '-0.02em',
  },
  scoreName: {
    padding: '8px 14px',
    borderRadius: '2px',
    fontSize: '12px',
    fontWeight: '700',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    border: '1px solid',
  },

  // ─── Player Tabs ─────────────────────────────────────────────────────────
  playerTabs: {
    display: 'flex',
    gap: '4px',
    marginBottom: '20px',
    overflowX: 'auto',
    scrollbarWidth: 'none',
  },
  playerTab: {
    padding: '10px 14px',
    fontSize: '13px',
    fontWeight: '700',
    borderRadius: '2px',
    border: `1px solid ${C.borderMid}`,
    whiteSpace: 'nowrap',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    background: 'transparent',
    color: C.textSec,
    cursor: 'pointer',
  },
  playerTabScore: {
    background: C.surface2,
    color: C.gold,
    padding: '2px 6px',
    borderRadius: '2px',
    fontSize: '11px',
    fontWeight: '800',
  },

  // ─── Scoring Section ─────────────────────────────────────────────────────
  scoringSection: {
    marginBottom: '24px',
  },
  fieldLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: C.textSec,
    textTransform: 'uppercase',
    fontWeight: '700',
    marginBottom: '14px',
    textAlign: 'center',
  },

  // ─── Big Score Input ─────────────────────────────────────────────────────
  bigScoreContainer: {
    position: 'relative',
    marginBottom: '4px',
    background: C.surface1,
    borderRadius: '6px',
    border: `1px solid ${C.borderMid}`,
    userSelect: 'none',
    overflow: 'hidden',
    minHeight: '140px',
  },
  bigScoreHalves: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    pointerEvents: 'none',
  },
  bigScoreLeftHalf: {
    flex: 1,
    background: 'rgba(201,162,40,0.04)',
  },
  bigScoreRightHalf: {
    flex: 1,
    background: 'rgba(201,162,40,0.10)',
  },
  bigScoreSideAbs: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    color: C.textMuted,
    pointerEvents: 'none',
    zIndex: 1,
  },
  bigScoreSideLabel: {
    fontSize: '14px',
    fontWeight: '800',
    letterSpacing: '0.02em',
    color: C.textMuted,
  },
  bigScoreCenter: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px 80px',
    pointerEvents: 'none',
    zIndex: 1,
    minHeight: '140px',
  },
  bigScoreValue: {
    fontFamily: F,
    fontSize: '64px',
    fontWeight: '800',
    color: C.textPrimary,
    textAlign: 'center',
    lineHeight: 1,
    letterSpacing: '-0.04em',
  },
  bigScoreHint: {
    fontSize: '10px',
    letterSpacing: '0.12em',
    color: C.gold,
    marginTop: '8px',
    fontWeight: '700',
    textAlign: 'center',
    minHeight: '14px',
    textTransform: 'uppercase',
  },
  bigScoreTapZone: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '50%',
    background: 'transparent',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    zIndex: 2,
  },

  // ─── Stats Section (Scoring screen detail rows) ───────────────────────────
  statsSection: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    marginBottom: '24px',
    overflow: 'hidden',
  },
  statRow: {
    padding: '14px 16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: `1px solid ${C.border}`,
    gap: '12px',
  },
  statRowLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    color: C.textSec,
    fontWeight: '600',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    minWidth: '60px',
  },
  autoBadge: {
    fontSize: '9px',
    letterSpacing: '0.15em',
    color: C.greenAccent,
    background: C.greenBg,
    padding: '2px 6px',
    borderRadius: '2px',
    fontWeight: '700',
    textTransform: 'uppercase',
  },

  // ─── Steppers ────────────────────────────────────────────────────────────
  miniStepper: {
    display: 'flex',
    alignItems: 'center',
    background: C.surface2,
    border: `1px solid ${C.borderMid}`,
    borderRadius: '4px',
    overflow: 'hidden',
    height: '34px',
  },
  miniStepperTapZone: {
    width: '36px',
    height: '100%',
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: C.textPrimary,
    padding: 0,
    cursor: 'pointer',
  },
  miniStepperValue: {
    minWidth: '32px',
    fontSize: '15px',
    fontWeight: '800',
    color: C.textPrimary,
    textAlign: 'center',
    lineHeight: 1,
    borderLeft: `1px solid ${C.borderMid}`,
    borderRight: `1px solid ${C.borderMid}`,
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: C.surface1,
  },
  penaltyGroup: {
    display: 'flex',
    gap: '8px',
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  penaltyItem: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
  },
  penaltyStepper: {
    display: 'flex',
    alignItems: 'center',
    background: C.surface2,
    border: `1px solid ${C.borderMid}`,
    borderRadius: '4px',
    overflow: 'hidden',
    height: '34px',
    width: '100%',
  },
  penaltyStepperTapZone: {
    flex: 1,
    height: '100%',
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: C.textPrimary,
    padding: 0,
    cursor: 'pointer',
  },
  penaltyStepperValue: {
    minWidth: '40px',
    fontSize: '15px',
    fontWeight: '800',
    color: C.textPrimary,
    textAlign: 'center',
    lineHeight: 1,
    borderLeft: `1px solid ${C.borderMid}`,
    borderRight: `1px solid ${C.borderMid}`,
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: C.surface1,
    padding: '0 12px',
  },
  penaltyLabel: {
    fontSize: '12px',
    letterSpacing: '0.1em',
    color: C.textSec,
    fontWeight: '700',
    textAlign: 'center',
    margin: '0',
    textTransform: 'uppercase',
  },
  penaltyBadge: {
    fontSize: '12px',
    letterSpacing: '0.05em',
    color: C.white,
    background: C.error,
    padding: '2px 7px',
    borderRadius: '8px',
    fontWeight: '800',
  },
  penaltyTotalBadge: {
    fontSize: '12px',
    fontWeight: '800',
    color: C.error,
    background: C.errorBg,
    padding: '6px 10px',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '44px',
    textAlign: 'center',
  },

  // ─── Toggle Buttons ───────────────────────────────────────────────────────
  toggleRow: {
    display: 'flex',
    gap: '3px',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  toggleBtn: {
    padding: '5px 8px',
    borderRadius: '2px',
    border: `1px solid ${C.borderMid}`,
    fontSize: '10px',
    fontWeight: '700',
    display: 'flex',
    alignItems: 'center',
    gap: '3px',
    minHeight: '30px',
    minWidth: '0',
    whiteSpace: 'nowrap',
    background: 'transparent',
    color: C.textSec,
    cursor: 'pointer',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },

  // ─── Putt + Memo Row ─────────────────────────────────────────────────────
  puttMemoRow: {
    display: 'flex',
    width: '260px',
    gap: '8px',
    alignItems: 'center',
    flexShrink: 0,
  },

  // ─── Split Stepper ────────────────────────────────────────────────────────
  splitStepper: {
    position: 'relative',
    background: C.surface2,
    border: `1px solid ${C.borderMid}`,
    borderRadius: '4px',
    overflow: 'hidden',
    height: '34px',
    userSelect: 'none',
  },
  splitStepperHalves: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    pointerEvents: 'none',
  },
  splitStepperLeftHalf: {
    flex: 1,
    background: 'rgba(201,162,40,0.03)',
  },
  splitStepperRightHalf: {
    flex: 1,
    background: 'rgba(201,162,40,0.14)',
  },
  splitStepperContent: {
    position: 'relative',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
    zIndex: 1,
  },
  splitStepperValue: {
    fontSize: '15px',
    fontWeight: '800',
    color: C.textPrimary,
    lineHeight: 1,
    minWidth: '24px',
    textAlign: 'center',
  },
  splitStepperSideIcon: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    color: C.textMuted,
    pointerEvents: 'none',
    zIndex: 1,
    display: 'flex',
    alignItems: 'center',
  },
  splitStepperTapZone: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '50%',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    zIndex: 2,
  },
  puttStepper: {
    flex: 3,
    display: 'flex',
    alignItems: 'center',
    background: C.surface2,
    border: `1px solid ${C.borderMid}`,
    borderRadius: '4px',
    overflow: 'hidden',
    height: '34px',
  },
  puttStepperTapZone: {
    flex: 1,
    height: '100%',
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: C.textPrimary,
    padding: 0,
    cursor: 'pointer',
  },
  puttStepperValue: {
    minWidth: '40px',
    fontSize: '15px',
    fontWeight: '800',
    color: C.textPrimary,
    textAlign: 'center',
    lineHeight: 1,
    borderLeft: `1px solid ${C.borderMid}`,
    borderRight: `1px solid ${C.borderMid}`,
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: C.surface1,
    padding: '0 12px',
  },
  memoButton: {
    flex: 1,
    height: '34px',
    padding: '0 6px',
    background: 'transparent',
    border: `1.5px solid ${C.borderMid}`,
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    fontSize: '12px',
    fontWeight: '700',
    color: C.textSec,
    cursor: 'pointer',
    position: 'relative',
    transition: 'all 0.15s ease',
  },
  memoButtonFilled: {
    background: C.goldBg,
    borderColor: C.gold,
    color: C.gold,
  },
  memoDot: {
    position: 'absolute',
    top: '4px',
    right: '6px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: C.gold,
  },

  // ─── Memo Modal ───────────────────────────────────────────────────────────
  memoModalCard: {
    background: C.surface1,
    borderRadius: '8px',
    padding: '24px 22px 20px',
    width: '100%',
    maxWidth: '420px',
    boxShadow: '0 12px 40px rgba(0,0,0,0.7)',
    animation: 'modalSlideUp 0.25s ease-out',
    border: `1px solid ${C.borderMid}`,
  },
  memoModalHeader: {
    marginBottom: '14px',
    textAlign: 'center',
  },
  memoModalTitle: {
    fontSize: '18px',
    fontWeight: '800',
    color: C.textPrimary,
    letterSpacing: '-0.01em',
    marginBottom: '4px',
  },
  memoModalSub: {
    fontSize: '11px',
    color: C.textSec,
    fontWeight: '600',
  },
  memoTextarea: {
    width: '100%',
    minHeight: '160px',
    padding: '12px 14px',
    fontSize: '14px',
    fontFamily: F,
    color: C.textPrimary,
    border: `1.5px solid ${C.borderMid}`,
    borderRadius: '4px',
    background: C.surface2,
    resize: 'vertical',
    outline: 'none',
    lineHeight: 1.5,
  },
  memoCharCount: {
    fontSize: '11px',
    color: C.textMuted,
    textAlign: 'right',
    marginTop: '6px',
    marginBottom: '14px',
    fontWeight: '600',
  },
  memoSaveBtn: {
    flex: 1,
    padding: '14px',
    background: C.gold,
    color: C.textInverse,
    fontSize: '13px',
    fontWeight: '700',
    borderRadius: '4px',
    letterSpacing: '0.02em',
    border: 'none',
    cursor: 'pointer',
    fontFamily: F,
  },

  // ─── Notes / Memo List ───────────────────────────────────────────────────
  notesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  noteCard: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderLeft: `3px solid ${C.gold}`,
    borderRadius: '4px',
    padding: '14px 16px',
  },
  noteCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
    gap: '8px',
  },
  noteCardHole: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    fontSize: '13px',
    fontWeight: '800',
    color: C.textPrimary,
    letterSpacing: '0.02em',
  },
  noteCardPar: {
    fontSize: '10px',
    color: C.textSec,
    fontWeight: '600',
  },
  noteCardScore: {
    fontSize: '13px',
    fontWeight: '800',
  },
  noteCardBody: {
    fontSize: '13px',
    color: C.textSec,
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },

  // ─── Shot Shape ───────────────────────────────────────────────────────────
  shotShapeSection: {
    padding: '14px 16px',
    borderBottom: `1px solid ${C.border}`,
  },
  shotShapeSectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    color: C.textSec,
    fontWeight: '600',
    marginBottom: '10px',
  },
  shotShapeMatrixHeader: {
    display: 'flex',
    fontSize: '9px',
    color: C.textMuted,
    fontWeight: '700',
    letterSpacing: '0.05em',
    marginBottom: '6px',
    padding: '0 4px',
  },
  shotShapeMatrixCenter: {
    flex: 1,
    textAlign: 'center',
  },
  shotShapeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '5px',
  },
  shotShapeCell: {
    minHeight: '78px',
    padding: '6px 2px',
    borderRadius: '4px',
    border: `1.5px solid ${C.borderMid}`,
    fontWeight: '700',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '2px',
    transition: 'all 0.15s ease',
    cursor: 'pointer',
    background: 'transparent',
    color: C.textSec,
  },
  shotShapeCellLabel: {
    fontSize: '10px',
    fontWeight: '700',
    letterSpacing: '0.01em',
    lineHeight: 1.1,
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  shotShapeRow: {
    display: 'flex',
    gap: '3px',
    flex: 1,
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  shotShapeBtn: {
    flex: 1,
    minWidth: '32px',
    height: '32px',
    padding: '2px 2px',
    borderRadius: '3px',
    border: `1.5px solid ${C.borderMid}`,
    fontWeight: '700',
    fontSize: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s ease',
    cursor: 'pointer',
    background: 'transparent',
    color: C.textSec,
  },
  shotShapeLabel: {
    fontSize: '10px',
    fontWeight: '700',
    letterSpacing: '-0.02em',
    lineHeight: 1,
    whiteSpace: 'nowrap',
  },
  fairwayHitRow: {
    display: 'flex',
    gap: '3px',
    flex: 1,
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  fairwayHitBtn: {
    flex: 1,
    minWidth: '34px',
    height: '32px',
    borderRadius: '3px',
    border: `1.5px solid ${C.borderMid}`,
    fontSize: '12px',
    fontWeight: '800',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    letterSpacing: '0.05em',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    padding: '2px',
    background: 'transparent',
    color: C.textSec,
  },

  // ─── Scoring Navigation ───────────────────────────────────────────────────
  scoringNav: {
    display: 'flex',
    gap: '10px',
    marginTop: '20px',
  },
  navBtn: {
    flex: 1,
    padding: '14px',
    background: 'transparent',
    border: `1px solid ${C.borderMid}`,
    color: C.textPrimary,
    fontSize: '13px',
    fontWeight: '700',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    borderRadius: '2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
    cursor: 'pointer',
    fontFamily: F,
  },
  finishBtn: {
    flex: 1,
    padding: '14px',
    background: C.gold,
    color: C.textInverse,
    fontSize: '13px',
    fontWeight: '700',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    borderRadius: '2px',
    border: 'none',
    cursor: 'pointer',
    fontFamily: F,
  },

  // ─── Analysis / Report ────────────────────────────────────────────────────
  reportHero: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    padding: '28px 24px',
    marginBottom: '24px',
    textAlign: 'center',
    boxShadow: '0 4px 16px rgba(0,0,0,0.4)',
  },
  reportDate: {
    fontSize: '11px',
    letterSpacing: '0.2em',
    color: C.textSec,
    textTransform: 'uppercase',
    marginBottom: '8px',
    fontWeight: '700',
  },
  reportCourse: {
    fontFamily: F,
    fontSize: '22px',
    fontWeight: '700',
    color: C.textPrimary,
    margin: '0 0 20px',
    letterSpacing: '-0.01em',
  },
  bigScoreDisplay: {
    padding: '16px 0',
  },
  bigScoreNum: {
    fontFamily: F,
    fontSize: '64px',
    fontWeight: '800',
    color: C.textPrimary,
    lineHeight: 1,
    letterSpacing: '-0.04em',
  },
  bigScoreDiff: {
    fontSize: '18px',
    fontWeight: '700',
    marginTop: '4px',
  },
  bigScoreLabel: {
    fontSize: '11px',
    color: C.textSec,
    letterSpacing: '0.15em',
    marginTop: '6px',
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  nineGrid: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '40px',
    marginTop: '20px',
    paddingTop: '20px',
    borderTop: `1px solid ${C.border}`,
  },
  nineItem: {
    textAlign: 'center',
  },
  nineDivider: {
    width: '1px',
    height: '40px',
    background: C.border,
  },
  nineLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: C.textSec,
    fontWeight: '700',
    marginBottom: '4px',
    textTransform: 'uppercase',
  },
  nineValue: {
    fontFamily: F,
    fontSize: '22px',
    fontWeight: '800',
    color: C.textPrimary,
    letterSpacing: '-0.02em',
  },
  keyStatsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '8px',
  },
  statTile: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    padding: '16px 14px',
    textAlign: 'center',
    boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
  },
  tileLabel: {
    fontSize: '10px',
    letterSpacing: '0.2em',
    color: C.textSec,
    textTransform: 'uppercase',
    marginBottom: '8px',
    fontWeight: '700',
  },
  tileValue: {
    fontFamily: F,
    fontSize: '28px',
    fontWeight: '800',
    color: C.textPrimary,
    lineHeight: 1,
    letterSpacing: '-0.03em',
  },
  tileSub: {
    fontSize: '11px',
    color: C.textMuted,
    marginTop: '6px',
    fontWeight: '500',
  },
  breakdownList: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    padding: '16px',
  },
  breakdownRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '8px 0',
  },
  breakdownLabel: {
    width: '70px',
    fontSize: '12px',
    color: C.textSec,
    fontWeight: '600',
  },
  breakdownBarTrack: {
    flex: 1,
    height: '5px',
    background: C.surface3,
    borderRadius: '3px',
    overflow: 'hidden',
  },
  breakdownBarFill: {
    height: '100%',
    borderRadius: '3px',
    transition: 'width 0.4s ease-out',
  },
  breakdownCount: {
    width: '24px',
    textAlign: 'right',
    fontSize: '13px',
    fontWeight: '700',
    color: C.textPrimary,
  },

  // ─── Scorecard Table ──────────────────────────────────────────────────────
  scorecardWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  scorecardTable: {
    background: C.surface1,
    border: `1px solid ${C.borderMid}`,
    borderRadius: '4px',
    overflow: 'hidden',
  },
  scorecardTableRow: {
    display: 'flex',
    alignItems: 'stretch',
    borderBottom: `1px solid ${C.border}`,
    minHeight: '30px',
  },
  scorecardRowLabel: {
    width: '54px',
    flexShrink: 0,
    background: C.surface2,
    borderRight: `1px solid ${C.borderMid}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    letterSpacing: '0.1em',
    fontWeight: '700',
    color: C.textSec,
  },
  scorecardRowLabelHeader: {
    background: C.hero,
    color: C.gold,
    fontSize: '11px',
    letterSpacing: '0.1em',
    whiteSpace: 'normal',
    wordBreak: 'break-word',
    lineHeight: '1.25',
    textAlign: 'center',
    padding: '4px 3px',
  },
  scorecardTableCells: {
    display: 'grid',
    gridTemplateColumns: 'repeat(9, 1fr)',
    flex: 1,
    minWidth: 0,
  },
  scorecardHeaderCell: {
    padding: '6px 0',
    fontSize: '12px',
    fontWeight: '700',
    color: C.textSec,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: `1px solid ${C.border}`,
    minWidth: 0,
  },
  scorecardParCell: {
    padding: '5px 0',
    fontSize: '12px',
    fontWeight: '600',
    color: C.textMuted,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: `1px solid ${C.border}`,
    minWidth: 0,
  },
  scorecardScoreCell: {
    padding: '3px 2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: `1px solid ${C.border}`,
    minWidth: 0,
  },
  scorecardPuttCell: {
    padding: '5px 0',
    fontSize: '11px',
    fontWeight: '600',
    color: C.textMuted,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: `1px solid ${C.border}`,
    minWidth: 0,
  },
  scorecardTotalCell: {
    width: '58px',
    flexShrink: 0,
    background: C.surface2,
    borderLeft: `1.5px solid ${C.borderMid}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: '700',
    color: C.textPrimary,
    gap: '3px',
  },
  scorecardTotalHeader: {
    background: C.hero,
    color: C.gold,
    fontSize: '10px',
    letterSpacing: '0.15em',
  },
  scorecardTotalDiff: {
    fontSize: '10px',
    fontWeight: '600',
    opacity: 0.7,
  },
  scorecardGrandTotal: {
    background: `linear-gradient(135deg, ${C.hero} 0%, #0f2218 100%)`,
    color: C.textPrimary,
    borderRadius: '4px',
    padding: '14px 16px',
    textAlign: 'center',
    border: `1px solid ${C.heroBorder}`,
  },
  scorecardGrandRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  scorecardGrandLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: C.gold,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  scorecardGrandValues: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    gap: '8px',
  },
  scorecardGrandItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
  },
  scorecardGrandItemLabel: {
    fontSize: '9px',
    letterSpacing: '0.15em',
    color: C.gold,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  scorecardGrandItemValue: {
    fontFamily: F,
    fontSize: '20px',
    fontWeight: '800',
    color: C.textPrimary,
    lineHeight: 1,
    letterSpacing: '-0.02em',
  },

  // ─── Insights ────────────────────────────────────────────────────────────
  insightsList: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    padding: '6px 0',
  },
  insightRow: {
    display: 'flex',
    gap: '12px',
    padding: '14px 16px',
    borderBottom: `1px solid ${C.border}`,
    alignItems: 'flex-start',
  },
  insightIcon: {
    fontSize: '18px',
  },
  insightText: {
    flex: 1,
    fontSize: '13px',
    lineHeight: 1.5,
    color: C.textSec,
  },

  // ─── History ─────────────────────────────────────────────────────────────
  historyList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  historyCard: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'stretch',
    overflow: 'hidden',
    boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
  },
  historyCardMain: {
    flex: 1,
    padding: '16px 18px',
    background: 'transparent',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    textAlign: 'left',
    border: 'none',
    cursor: 'pointer',
  },
  historyCardLeft: {
    flex: 1,
  },
  historyCourse: {
    fontSize: '15px',
    fontWeight: '700',
    color: C.textPrimary,
    marginBottom: '4px',
  },
  historyMeta: {
    fontSize: '12px',
    color: C.textSec,
  },
  historyCardRight: {
    textAlign: 'right',
    marginLeft: '16px',
  },
  historyScore: {
    fontFamily: F,
    fontSize: '24px',
    fontWeight: '800',
    color: C.textPrimary,
    lineHeight: 1,
    letterSpacing: '-0.03em',
  },
  historyDiff: {
    fontSize: '12px',
    fontWeight: '700',
    marginTop: '2px',
  },
  deleteBtn: {
    padding: '0 16px',
    background: 'transparent',
    borderLeft: `1px solid ${C.border}`,
    color: C.error,
    display: 'flex',
    alignItems: 'center',
    border: 'none',
    cursor: 'pointer',
    borderLeft: `1px solid ${C.border}`,
  },

  // ─── Empty State ─────────────────────────────────────────────────────────
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
  },
  emptyIcon: {
    fontSize: '48px',
    marginBottom: '16px',
    opacity: 0.5,
  },
  emptyTitle: {
    fontSize: '16px',
    fontWeight: '700',
    color: C.textSec,
    marginBottom: '6px',
  },
  emptySub: {
    fontSize: '13px',
    color: C.textMuted,
  },

  // ─── Trend Chart ─────────────────────────────────────────────────────────
  trendChart: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    padding: '16px',
    display: 'flex',
    alignItems: 'flex-end',
    gap: '8px',
    height: '180px',
    overflowX: 'auto',
  },
  trendCol: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    minWidth: '40px',
    height: '100%',
    position: 'relative',
  },
  trendValue: {
    fontSize: '11px',
    fontWeight: '700',
    color: C.textPrimary,
    marginBottom: '4px',
  },
  trendBar: {
    width: '18px',
    background: C.gold,
    borderRadius: '2px 2px 0 0',
    minHeight: '8px',
  },
  trendDate: {
    fontSize: '9px',
    color: C.textMuted,
    marginTop: '6px',
    textAlign: 'center',
  },

  // ─── Bottom Tab Bar ───────────────────────────────────────────────────────
  tabBar: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    background: C.surface1,
    borderTop: `1px solid ${C.borderMid}`,
    boxShadow: '0 -4px 24px rgba(0,0,0,0.5)',
    zIndex: 100,
    paddingBottom: 'env(safe-area-inset-bottom, 0)',
  },
  tabBarInner: {
    maxWidth: '520px',
    margin: '0 auto',
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
  },
  tabBarBtn: {
    background: 'transparent',
    border: 'none',
    padding: '10px 2px 12px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    position: 'relative',
    cursor: 'pointer',
    transition: 'color 0.15s ease',
    minHeight: '56px',
  },
  tabBarBtnHome: {
    padding: '6px 2px 12px',
  },
  tabBarLabel: {
    fontSize: '9px',
    letterSpacing: '0.06em',
    lineHeight: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '100%',
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  tabBarActiveIndicator: {
    position: 'absolute',
    top: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '28px',
    height: '2px',
    background: C.gold,
    borderRadius: '0 0 2px 2px',
  },

  // ─── Insights View ────────────────────────────────────────────────────────
  insightsBanner: {
    background: `linear-gradient(135deg, ${C.hero} 0%, #0f2218 100%)`,
    color: C.textPrimary,
    borderRadius: '4px',
    padding: '18px 20px',
    marginBottom: '24px',
    textAlign: 'center',
    border: `1px solid ${C.heroBorder}`,
    boxShadow: '0 4px 20px rgba(0,0,0,0.5)',
  },
  insightsBannerLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: C.gold,
    fontWeight: '700',
    marginBottom: '8px',
    textTransform: 'uppercase',
  },
  insightsBannerValue: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: '4px',
    fontSize: '28px',
    fontWeight: '800',
    letterSpacing: '-0.02em',
    color: C.textPrimary,
  },
  insightsBannerSub: {
    fontSize: '11px',
    fontWeight: '700',
    color: C.textSec,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  insightsBannerDot: {
    color: C.heroBorder,
    margin: '0 8px',
    fontSize: '20px',
  },

  // ─── Style Card (Insights player archetype) ───────────────────────────────
  styleCard: {
    background: C.surface1,
    border: `2px solid ${C.borderMid}`,
    borderRadius: '6px',
    padding: '20px',
    display: 'flex',
    gap: '16px',
    alignItems: 'flex-start',
    marginBottom: '10px',
  },
  styleIconWrap: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    background: C.surface2,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  styleIconEmoji: {
    fontSize: '30px',
    lineHeight: 1,
  },
  styleContent: {
    flex: 1,
    minWidth: 0,
  },
  styleType: {
    fontSize: '15px',
    fontWeight: '800',
    letterSpacing: '-0.01em',
    marginBottom: '4px',
    lineHeight: 1.2,
    color: C.textPrimary,
  },
  styleSubtitle: {
    fontSize: '12px',
    color: C.textSec,
    fontWeight: '600',
    marginBottom: '10px',
    lineHeight: 1.4,
  },
  styleDescription: {
    fontSize: '12px',
    color: C.textSec,
    lineHeight: 1.6,
  },
  styleMetrics: {
    display: 'flex',
    background: C.surface2,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    padding: '12px 4px',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  styleMetric: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    padding: '0 4px',
    minWidth: 0,
  },
  styleMetricLabel: {
    fontSize: '9px',
    letterSpacing: '0.1em',
    color: C.textMuted,
    fontWeight: '700',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  styleMetricValue: {
    fontSize: '18px',
    fontWeight: '800',
    color: C.textPrimary,
    letterSpacing: '-0.02em',
    lineHeight: 1,
  },
  styleMetricDivider: {
    width: '1px',
    height: '28px',
    background: C.border,
    flexShrink: 0,
  },
  insightCards: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  insightCard: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderLeft: '3px solid',
    borderRadius: '4px',
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
  },
  insightCardBadge: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    background: C.greenBg,
    color: C.greenAccent,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '800',
    fontSize: '14px',
    flexShrink: 0,
  },
  insightCardContent: {
    flex: 1,
  },
  insightCardTitle: {
    fontSize: '14px',
    fontWeight: '700',
    color: C.textPrimary,
    marginBottom: '4px',
  },
  insightCardDetail: {
    fontSize: '12px',
    color: C.textSec,
    lineHeight: 1.5,
  },
  parAnalysis: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    overflow: 'hidden',
  },
  parAnalysisRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '14px 16px',
    borderBottom: `1px solid ${C.border}`,
    gap: '14px',
  },
  parAnalysisBadge: {
    background: C.hero,
    color: C.gold,
    padding: '6px 10px',
    borderRadius: '2px',
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '0.08em',
    minWidth: '52px',
    textAlign: 'center',
    border: `1px solid ${C.heroBorder}`,
  },
  parAnalysisData: {
    flex: 1,
  },
  parAnalysisMain: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
  },
  parAnalysisStrokes: {
    fontSize: '20px',
    fontWeight: '800',
    color: C.textPrimary,
    letterSpacing: '-0.02em',
  },
  parAnalysisDiff: {
    fontSize: '13px',
    fontWeight: '700',
  },
  parAnalysisCount: {
    fontSize: '11px',
    color: C.textSec,
    marginLeft: 'auto',
  },
  parAnalysisRates: {
    fontSize: '11px',
    color: C.textMuted,
    marginTop: '4px',
  },
  parAnalysisDot: {
    color: C.textMuted,
    margin: '0 6px',
  },
  paceCard: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    padding: '18px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '10px',
  },
  paceRow: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
    flex: 1,
  },
  paceLabel: {
    fontSize: '10px',
    letterSpacing: '0.2em',
    color: C.textSec,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  paceValue: {
    fontSize: '24px',
    fontWeight: '800',
    color: C.textPrimary,
    letterSpacing: '-0.02em',
  },
  paceSub: {
    fontSize: '10px',
    color: C.textSec,
    fontWeight: '500',
    marginLeft: '3px',
  },
  paceArrow: {
    fontSize: '28px',
    color: C.greenAccent,
    fontWeight: '300',
    padding: '0 14px',
  },
  paceInsight: {
    padding: '12px 14px',
    background: C.surface2,
    borderRadius: '4px',
    fontSize: '12px',
    color: C.textSec,
    lineHeight: 1.5,
    textAlign: 'center',
  },

  // ─── My Bag ───────────────────────────────────────────────────────────────
  bagBanner: {
    background: `linear-gradient(135deg, ${C.hero} 0%, #0f2218 100%)`,
    color: C.textPrimary,
    borderRadius: '4px',
    padding: '18px 20px',
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
    border: `1px solid ${C.heroBorder}`,
    boxShadow: '0 4px 16px rgba(0,0,0,0.4)',
  },
  bagBannerIcon: {
    fontSize: '32px',
  },
  bagBannerLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: C.gold,
    fontWeight: '700',
    marginBottom: '4px',
    textTransform: 'uppercase',
  },
  bagBannerValue: {
    fontSize: '26px',
    fontWeight: '800',
    letterSpacing: '-0.02em',
    color: C.textPrimary,
  },
  bagBannerSub: {
    fontSize: '11px',
    color: C.textSec,
    fontWeight: '600',
    letterSpacing: '0.08em',
  },
  bagHint: {
    fontSize: '11px',
    color: C.textMuted,
    textAlign: 'center',
    marginBottom: '20px',
    fontStyle: 'italic',
  },

  // ─── Club Card ────────────────────────────────────────────────────────────
  clubList: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    overflow: 'hidden',
  },
  clubCard: {
    padding: '14px 16px',
    borderBottom: `1px solid ${C.border}`,
  },
  clubCardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '10px',
  },
  clubName: {
    fontSize: '15px',
    fontWeight: '800',
    color: C.textPrimary,
    letterSpacing: '-0.01em',
  },
  clubRunBadge: {
    background: C.goldBg,
    color: C.gold,
    border: `1px solid ${C.goldMuted}`,
    padding: '3px 8px',
    borderRadius: '2px',
    fontSize: '10px',
    fontWeight: '700',
    letterSpacing: '0.06em',
    textTransform: 'uppercase',
  },
  clubFieldRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '6px 0',
    gap: '12px',
  },
  clubFieldLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
    minWidth: 0,
  },
  clubFieldLabelMain: {
    fontSize: '13px',
    fontWeight: '700',
    color: C.textPrimary,
  },
  clubFieldLabelSub: {
    fontSize: '9px',
    letterSpacing: '0.12em',
    color: C.textMuted,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  clubStepper: {
    display: 'flex',
    alignItems: 'center',
    background: C.surface2,
    border: `1px solid ${C.borderMid}`,
    borderRadius: '4px',
    overflow: 'hidden',
    height: '34px',
    flexShrink: 0,
  },
  clubStepperHighlight: {
    borderColor: C.gold,
    background: C.goldBg,
  },
  clubStepperValue: {
    minWidth: '80px',
    fontSize: '13px',
    fontWeight: '700',
    color: C.textPrimary,
    textAlign: 'center',
    lineHeight: 1,
    borderLeft: `1px solid ${C.borderMid}`,
    borderRight: `1px solid ${C.borderMid}`,
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '3px',
    background: C.surface1,
    padding: '0 8px',
  },
  clubAvgNum: {
    fontSize: '15px',
    fontWeight: '800',
    letterSpacing: '-0.02em',
    color: C.textPrimary,
  },
  clubAvgUnit: {
    fontSize: '10px',
    fontWeight: '600',
    color: C.textMuted,
    letterSpacing: '0.05em',
  },

  // ─── Distance Chart ───────────────────────────────────────────────────────
  distanceChartLegend: {
    display: 'flex',
    justifyContent: 'center',
    gap: '20px',
    marginBottom: '10px',
    fontSize: '11px',
    color: C.textSec,
    fontWeight: '600',
  },
  distanceLegendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  distanceLegendDot: {
    width: '10px',
    height: '10px',
    borderRadius: '2px',
  },
  distanceChart: {
    background: C.surface1,
    border: `1px solid ${C.border}`,
    borderRadius: '4px',
    padding: '14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  distanceRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  distanceLabel: {
    width: '62px',
    fontSize: '12px',
    fontWeight: '700',
    color: C.textSec,
    flexShrink: 0,
  },
  distanceBarTrack: {
    flex: 1,
    height: '18px',
    background: C.surface3,
    borderRadius: '3px',
    overflow: 'hidden',
    position: 'relative',
  },
  distanceBarFillTotal: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    background: C.hero,
    borderRadius: '3px',
    transition: 'width 0.4s ease',
    border: `1px solid ${C.heroBorder}`,
  },
  distanceBarFillCarry: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    background: C.greenAccent,
    borderRadius: '3px',
    transition: 'width 0.4s ease',
    zIndex: 1,
    opacity: 0.75,
  },
  distanceValues: {
    width: '68px',
    textAlign: 'right',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '0',
    lineHeight: 1.1,
  },
  distanceValueCarry: {
    fontSize: '10px',
    fontWeight: '600',
    color: C.greenAccent,
  },
  distanceValueTotal: {
    fontSize: '13px',
    fontWeight: '800',
    color: C.textPrimary,
    letterSpacing: '-0.02em',
  },

  // ─── Modal ────────────────────────────────────────────────────────────────
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: C.scrim,
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    zIndex: 1000,
    animation: 'modalFadeIn 0.2s ease-out',
  },
  modalCard: {
    background: C.surface1,
    borderRadius: '8px',
    padding: '28px 24px 20px',
    width: '100%',
    maxWidth: '340px',
    textAlign: 'center',
    boxShadow: '0 12px 48px rgba(0,0,0,0.8)',
    animation: 'modalSlideUp 0.25s ease-out',
    border: `1px solid ${C.borderMid}`,
  },
  modalIcon: {
    fontSize: '40px',
    marginBottom: '8px',
  },
  modalTitle: {
    fontSize: '17px',
    fontWeight: '800',
    color: C.textPrimary,
    marginBottom: '8px',
    letterSpacing: '-0.01em',
  },
  modalText: {
    fontSize: '13px',
    color: C.textSec,
    lineHeight: 1.5,
    marginBottom: '20px',
  },
  modalActions: {
    display: 'flex',
    gap: '8px',
  },
  modalBtnCancel: {
    flex: 1,
    padding: '14px',
    background: C.surface2,
    color: C.textPrimary,
    fontSize: '13px',
    fontWeight: '700',
    borderRadius: '4px',
    letterSpacing: '0.02em',
    border: `1px solid ${C.borderMid}`,
    cursor: 'pointer',
    fontFamily: F,
  },
  modalBtnConfirm: {
    flex: 1,
    padding: '14px',
    background: C.error,
    color: C.white,
    fontSize: '13px',
    fontWeight: '700',
    borderRadius: '4px',
    letterSpacing: '0.02em',
    border: 'none',
    cursor: 'pointer',
    fontFamily: F,
  },
  modalBtnPrimary: {
    flex: 1,
    padding: '14px',
    background: C.gold,
    color: C.textInverse,
    fontSize: '13px',
    fontWeight: '700',
    borderRadius: '4px',
    letterSpacing: '0.02em',
    border: 'none',
    cursor: 'pointer',
    fontFamily: F,
  },

  // ─── Club Card extras ─────────────────────────────────────────────────────
  clubNameEditWrap: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    flex: 1,
  },
  clubNameInput: {
    flex: 1,
    padding: '6px 10px',
    fontSize: '15px',
    fontWeight: '800',
    background: C.surface2,
    border: `1.5px solid ${C.gold}`,
    borderRadius: '4px',
    color: C.textPrimary,
    outline: 'none',
    fontFamily: F,
    letterSpacing: '-0.01em',
  },
  clubNameActionBtn: {
    width: '30px',
    height: '30px',
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: C.greenAccent,
    cursor: 'pointer',
    borderRadius: '4px',
    padding: 0,
  },
  clubNameTappable: {
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    cursor: 'pointer',
    padding: 0,
    flex: 1,
    textAlign: 'left',
  },
  clubCardHeaderRight: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    flexShrink: 0,
  },
  clubDeleteBtn: {
    width: '28px',
    height: '28px',
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: C.error,
    cursor: 'pointer',
    borderRadius: '4px',
    padding: 0,
    opacity: 0.7,
  },
  clubGripHandle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '24px',
    height: '32px',
    color: C.textMuted,
    cursor: 'grab',
    flexShrink: 0,
    touchAction: 'none',
    userSelect: 'none',
    WebkitUserSelect: 'none',
  },
};

export default styles;
