const styles = {
  app: {
    minHeight: '100vh',
    background: '#faf6ee',
    fontFamily: "'Noto Sans KR', -apple-system, sans-serif",
    color: '#3a3a3a',
    paddingBottom: '0',
    width: '100%',
    overflowX: 'hidden',
  },
  container: {
    width: '100%',
    maxWidth: '520px',
    margin: '0 auto',
    padding: '20px 8px 100px',
    animation: 'fadeIn 0.3s ease-out',
    boxSizing: 'border-box',
  },
  header: {
    padding: '12px 0 24px',
  },
  headerTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  userSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  actionButton: {
    background: 'none',
    border: 'none',
    padding: '4px 6px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#8b8574',
    cursor: 'pointer',
    transition: 'color 0.2s ease',
  },
  userName: {
    fontSize: '13px',
    fontWeight: '600',
    color: '#1f3d2e',
  },
  logoutButton: {
    background: 'none',
    border: 'none',
    padding: '4px 8px',
    display: 'flex',
    alignItems: 'center',
    color: '#8b8574',
    cursor: 'pointer',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  logoMark: {
    fontSize: '26px',
  },
  brandName: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '20px',
    fontWeight: '800',
    letterSpacing: '0.05em',
    color: '#1f3d2e',
    lineHeight: 1,
  },
  brandTagline: {
    fontSize: '10px',
    letterSpacing: '0.2em',
    color: '#8b8574',
    textTransform: 'uppercase',
    marginTop: '3px',
  },
  dateLine: {
    fontSize: '12px',
    color: '#6b6558',
    marginTop: '18px',
    letterSpacing: '0.05em',
  },
  // ===== LOGIN SCREEN =====
  loginCard: {
    background: '#fff',
    padding: '40px 28px',
    borderRadius: '4px',
    textAlign: 'center',
    marginTop: '60px',
  },
  loginLogo: {
    fontSize: '60px',
    marginBottom: '20px',
  },
  loginTitle: {
    fontSize: '28px',
    fontWeight: '800',
    color: '#1f3d2e',
    margin: '0 0 8px',
  },
  loginSubtitle: {
    fontSize: '14px',
    color: '#8b8574',
    margin: '0 0 40px',
  },
  loginForm: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  heroCard: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    padding: '28px 24px',
    borderRadius: '4px',
    marginBottom: '18px',
    position: 'relative',
    overflow: 'hidden',
    textAlign: 'center',
  },
  heroLabel: {
    fontSize: '10px',
    letterSpacing: '0.3em',
    color: '#a8c2a5',
    marginBottom: '14px',
    fontWeight: '700',
  },
  heroTitle: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '28px',
    fontWeight: '800',
    margin: '0 0 24px',
    lineHeight: 1.3,
    letterSpacing: '-0.02em',
  },
  heroButton: {
    background: '#f5f0e6',
    color: '#1f3d2e',
    padding: '14px 20px',
    borderRadius: '2px',
    fontSize: '13px',
    fontWeight: '600',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '8px',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
    marginBottom: '24px',
  },
  statCard: {
    background: '#fff',
    padding: '18px 16px',
    borderRadius: '3px',
    border: '1px solid #ebe4d3',
    textAlign: 'center',
  },
  statLabel: {
    fontSize: '10px',
    letterSpacing: '0.15em',
    color: '#8b8574',
    textTransform: 'uppercase',
    marginBottom: '8px',
    fontWeight: '600',
  },
  statValue: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '30px',
    fontWeight: '700',
    color: '#1f3d2e',
    lineHeight: 1,
  },
  section: {
    marginBottom: '28px',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '12px',
  },
  sectionTitle: {
    fontSize: '11px',
    letterSpacing: '0.2em',
    color: '#6b6558',
    textTransform: 'uppercase',
    fontWeight: '600',
    marginBottom: '12px',
  },
  textLink: {
    background: 'none',
    fontSize: '12px',
    color: '#1f3d2e',
    textDecoration: 'underline',
    textUnderlineOffset: '3px',
  },
  roundRow: {
    background: '#fff',
    width: '100%',
    padding: '16px 18px',
    borderRadius: '3px',
    border: '1px solid #ebe4d3',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    textAlign: 'left',
  },
  roundRowLeft: {
    flex: 1,
  },
  roundCourse: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#1f3d2e',
    marginBottom: '4px',
  },
  roundDate: {
    fontSize: '12px',
    color: '#8b8574',
  },
  dot: { color: '#c8c0b0' },
  roundRowRight: {
    textAlign: 'right',
  },
  roundScore: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '26px',
    fontWeight: '800',
    color: '#1f3d2e',
    lineHeight: 1,
    letterSpacing: '-0.02em',
  },
  roundDiff: {
    fontSize: '12px',
    fontWeight: '600',
    marginTop: '2px',
  },
  navGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '10px',
    marginTop: '8px',
  },
  navCard: {
    background: 'transparent',
    padding: '20px 16px',
    borderRadius: '3px',
    border: '1px solid #d4ccbb',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '10px',
    color: '#1f3d2e',
    fontSize: '12px',
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    fontWeight: '600',
  },
  pageHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 0 24px',
  },
  pageTitle: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '20px',
    fontWeight: '800',
    color: '#1f3d2e',
    letterSpacing: '-0.01em',
  },
  iconBack: {
    width: '40px',
    height: '40px',
    background: 'transparent',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#1f3d2e',
  },
  formSection: {
    marginBottom: '24px',
  },
  formLabel: {
    display: 'block',
    fontSize: '11px',
    letterSpacing: '0.2em',
    color: '#6b6558',
    textTransform: 'uppercase',
    fontWeight: '600',
    marginBottom: '10px',
  },
  formLabelRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '10px',
  },
  formInput: {
    width: '100%',
    padding: '13px 14px',
    fontSize: '15px',
    border: '1px solid #d4ccbb',
    borderRadius: '2px',
    background: '#fff',
    color: '#1f3d2e',
    outline: 'none',
    marginBottom: '10px',
  },
  addButton: {
    background: 'transparent',
    color: '#1f3d2e',
    fontSize: '12px',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  playerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    marginBottom: '10px',
  },
  playerBadge: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    background: '#1f3d2e',
    color: '#f5f0e6',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: '600',
    flexShrink: 0,
  },
  removeButton: {
    width: '32px',
    height: '32px',
    background: 'transparent',
    color: '#8b8574',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  // ===== Par Setup (Table Style) =====
  parTableHint: {
    fontSize: '11px',
    color: '#8b8574',
    textAlign: 'center',
    marginBottom: '10px',
    fontStyle: 'italic',
  },
  parTable: {
    background: '#fff',
    border: '1px solid #d4ccbb',
    borderRadius: '4px',
    overflow: 'hidden',
    marginBottom: '10px',
  },
  parTableRow: {
    display: 'flex',
    alignItems: 'stretch',
    borderBottom: '1px solid #ebe4d3',
    minHeight: '36px',
  },
  parTableLabel: {
    width: '46px',
    flexShrink: 0,
    background: '#f5f0e6',
    borderRight: '1px solid #d4ccbb',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    letterSpacing: '0.1em',
    fontWeight: '700',
    color: '#6b6558',
  },
  parTableLabelHeader: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    fontSize: '11px',
    letterSpacing: '0.15em',
  },
  parTableCells: {
    display: 'grid',
    gridTemplateColumns: 'repeat(9, 1fr)',
    flex: 1,
    minWidth: 0,
  },
  parTableHoleCell: {
    padding: '6px 0',
    fontSize: '12px',
    fontWeight: '700',
    color: '#3a3a3a',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: '1px solid #ebe4d3',
    minWidth: 0,
  },
  parTableParCell: {
    padding: '4px 2px',
    borderRight: '1px solid #ebe4d3',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
    position: 'relative',
  },
  parTableParValue: {
    width: '26px',
    height: '26px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: '700',
    lineHeight: 1,
    transition: 'all 0.15s ease',
    pointerEvents: 'none',
    zIndex: 1,
  },
  parTapZone: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '50%',
    background: 'transparent',
    border: 'none',
    padding: 0,
    zIndex: 2,
  },
  parTableTotal: {
    width: '54px',
    flexShrink: 0,
    background: '#f5f0e6',
    borderLeft: '1.5px solid #d4ccbb',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: '800',
    color: '#1f3d2e',
  },
  parTableTotalHeader: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    fontSize: '10px',
    letterSpacing: '0.15em',
  },
  parLegend: {
    display: 'flex',
    justifyContent: 'space-around',
    gap: '8px',
    padding: '12px 8px',
    background: '#faf6ee',
    borderRadius: '3px',
    marginTop: '10px',
    flexWrap: 'wrap',
  },
  parLegendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '11px',
    color: '#6b6558',
    fontWeight: '600',
  },
  parLegendDot: {
    width: '22px',
    height: '22px',
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '12px',
    fontWeight: '700',
  },
  parSummary: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    borderRadius: '3px',
    padding: '18px 20px',
    marginBottom: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '20px',
  },
  parSummaryMain: {
    flex: 1,
    textAlign: 'center',
  },
  parSummaryLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: '#a8c2a5',
    fontWeight: '700',
    marginBottom: '4px',
  },
  parSummaryValue: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '38px',
    fontWeight: '800',
    lineHeight: 1,
    letterSpacing: '-0.02em',
  },
  parSummaryDivider: {
    width: '1px',
    height: '50px',
    background: '#4a5e51',
  },
  parSummaryNines: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: '90px',
  },
  parSummaryNineRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    gap: '12px',
  },
  parSummaryNineLabel: {
    fontSize: '10px',
    letterSpacing: '0.2em',
    color: '#a8c2a5',
    fontWeight: '600',
  },
  parSummaryNineValue: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '18px',
    fontWeight: '700',
    color: '#f5f0e6',
  },
  primaryButton: {
    width: '100%',
    padding: '16px',
    background: '#1f3d2e',
    color: '#f5f0e6',
    fontSize: '13px',
    fontWeight: '600',
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
    borderRadius: '2px',
    marginTop: '12px',
  },
  secondaryButton: {
    flex: 1,
    padding: '14px',
    background: 'transparent',
    border: '1px solid #1f3d2e',
    color: '#1f3d2e',
    fontSize: '12px',
    fontWeight: '600',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
    borderRadius: '2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
  },
  reportActions: {
    marginTop: '12px',
    marginBottom: '20px',
  },
  reportActionRow: {
    display: 'flex',
    gap: '10px',
    marginTop: '10px',
  },
  scoringHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '8px 0 16px',
  },
  scoringCourse: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#1f3d2e',
    letterSpacing: '-0.01em',
    textAlign: 'center',
  },
  progressBar: {
    marginBottom: '12px',
  },
  progressText: {
    display: 'flex',
    alignItems: 'baseline',
    marginBottom: '6px',
  },
  progressNumber: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '18px',
    fontWeight: '800',
    color: '#1f3d2e',
    lineHeight: 1,
  },
  progressTotal: {
    fontSize: '11px',
    color: '#8b8574',
    letterSpacing: '0.1em',
    marginLeft: '4px',
  },
  progressTrack: {
    height: '3px',
    background: '#ebe4d3',
    borderRadius: '2px',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: '#1f5e3a',
    borderRadius: '2px',
    transition: 'width 0.3s ease',
  },
  runningScore: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    borderRadius: '4px',
    padding: '14px 16px',
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'stretch',
    gap: '16px',
  },
  runningScoreMain: {
    flex: '0 0 auto',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: '100px',
  },
  runningScoreLabel: {
    fontSize: '9px',
    letterSpacing: '0.22em',
    color: '#a8c2a5',
    fontWeight: '700',
    marginBottom: '6px',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '100px',
    textAlign: 'center',
  },
  runningScoreValues: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: '8px',
  },
  runningScoreNumber: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '30px',
    fontWeight: '800',
    lineHeight: 1,
    color: '#f5f0e6',
    letterSpacing: '-0.02em',
  },
  runningScoreDiff: {
    fontSize: '14px',
    fontWeight: '700',
    letterSpacing: '0.02em',
  },
  runningScoreDivider: {
    width: '1px',
    background: '#4a5e51',
    flexShrink: 0,
  },
  runningScoreStats: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-around',
    gap: '8px',
  },
  runningScoreStat: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    minWidth: 0,
  },
  runningScoreStatLabel: {
    fontSize: '9px',
    letterSpacing: '0.2em',
    color: '#a8c2a5',
    fontWeight: '700',
  },
  runningScoreStatValue: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '18px',
    fontWeight: '700',
    color: '#f5f0e6',
    lineHeight: 1,
  },
  holeNavigator: {
    display: 'flex',
    flexDirection: 'column',
    gap: '14px',
    marginBottom: '4px',
    padding: '6px 0 16px',
  },
  holeNavTable: {
    background: '#fff',
    border: '1px solid #d4ccbb',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  holeNavTableRow: {
    display: 'flex',
    alignItems: 'stretch',
    borderBottom: '1px solid #ebe4d3',
    minHeight: '30px',
  },  holeNavRowLabel: {
    width: '48px',
    flexShrink: 0,
    background: '#f5f0e6',
    borderRight: '1px solid #d4ccbb',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    letterSpacing: '0.12em',
    fontWeight: '700',
    color: '#6b6558',
  },
  holeNavRowLabelHeader: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    fontSize: '11px',
    letterSpacing: '0.15em',
  },
  holeNavTableCells: {
    display: 'grid',
    gridTemplateColumns: 'repeat(9, 1fr)',
    flex: 1,
    minWidth: 0,
  },
  holeNavHoleCell: {
    background: 'transparent',
    border: 'none',
    borderRight: '1px solid #ebe4d3',
    padding: '6px 0',
    fontSize: '13px',
    fontWeight: '700',
    color: '#3a3a3a',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
  },
  holeNavParCell: {
    borderRight: '1px solid #ebe4d3',
    padding: '5px 0',
    fontSize: '12px',
    fontWeight: '600',
    color: '#6b6558',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
  },
  holeNavScoreCell: {
    background: 'transparent',
    border: 'none',
    borderRight: '1px solid #ebe4d3',
    padding: '4px 2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
    cursor: 'pointer',
  },
  scoreMarker: {
    width: '26px',
    height: '26px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    lineHeight: 1,
    position: 'relative',
  },
  markerBirdie: {
    borderRadius: '50%',
    border: '2px solid #d97706',
  },
  markerEagle: {
    borderRadius: '50%',
    border: '2px solid #d97706',
    boxShadow: '0 0 0 2px #fff, 0 0 0 3.5px #d97706',
  },
  markerHoleInOne: {
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #e8b54f 0%, #c88a2e 50%, #a66d1a 100%)',
    backgroundSize: '200% 200%',
    animation: 'holeInOneShine 3s ease-in-out infinite',
    boxShadow: '0 0 0 2px #fff, 0 0 0 3.5px #c88a2e, 0 2px 8px rgba(200, 138, 46, 0.4)',
    fontWeight: '800',
  },
  holeInOneStar: {
    position: 'absolute',
    top: '-8px',
    right: '-6px',
    fontSize: '10px',
    color: '#c88a2e',
    textShadow: '0 0 3px #fff, 0 1px 2px rgba(0,0,0,0.2)',
    lineHeight: 1,
  },
  markerPar: {},
  markerBogey: {
    border: '2px solid #1f3d2e',
    borderRadius: '2px',
  },
  markerDouble: {
    border: '2px solid #1f3d2e',
    borderRadius: '2px',
    boxShadow: '0 0 0 2px #fff, 0 0 0 3.5px #1f3d2e',
  },
  holeHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '24px 0 20px',
    borderTop: '1px solid #ebe4d3',
    borderBottom: '1px solid #ebe4d3',
    marginBottom: '24px',
  },
  holeLabel: {
    fontSize: '11px',
    letterSpacing: '0.25em',
    color: '#8b8574',
    fontWeight: '600',
    marginBottom: '4px',
  },
  holePar: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '30px',
    fontWeight: '800',
    color: '#1f3d2e',
    lineHeight: 1,
    letterSpacing: '-0.02em',
  },
  scoreName: {
    padding: '8px 14px',
    borderRadius: '2px',
    fontSize: '12px',
    fontWeight: '600',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    border: '1px solid',
  },
  playerTabs: {
    display: 'flex',
    gap: '4px',
    marginBottom: '20px',
    overflowX: 'auto',
    scrollbarWidth: 'none',
  },
  playerTab: {
    padding: '10px 14px',
    fontSize: '13px',
    fontWeight: '600',
    borderRadius: '2px',
    border: '1px solid',
    whiteSpace: 'nowrap',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  playerTabScore: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    padding: '2px 6px',
    borderRadius: '2px',
    fontSize: '11px',
  },
  scoringSection: {
    marginBottom: '24px',
  },
  fieldLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: '#8b8574',
    textTransform: 'uppercase',
    fontWeight: '600',
    marginBottom: '14px',
    textAlign: 'center',
  },
  bigScoreContainer: {
    position: 'relative',
    marginBottom: '4px',
    background: '#faf6ee',
    borderRadius: '6px',
    border: '1px solid #ebe4d3',
    userSelect: 'none',
    overflow: 'hidden',
    minHeight: '140px',
  },
  bigScoreHalves: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    pointerEvents: 'none',
  },
  bigScoreLeftHalf: {
    flex: 1,
    background: 'rgba(31, 61, 46, 0.04)',
  },
  bigScoreRightHalf: {
    flex: 1,
    background: 'rgba(31, 61, 46, 0.08)',
  },
  bigScoreSideAbs: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    color: '#5e7d6a',
    pointerEvents: 'none',
    zIndex: 1,
  },
  bigScoreSideLabel: {
    fontSize: '14px',
    fontWeight: '800',
    letterSpacing: '0.02em',
  },
  bigScoreCenter: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px 80px',
    pointerEvents: 'none',
    zIndex: 1,
    minHeight: '140px',
  },
  bigScoreValue: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '64px',
    fontWeight: '800',
    color: '#1f3d2e',
    textAlign: 'center',
    lineHeight: 1,
    letterSpacing: '-0.04em',
  },
  bigScoreHint: {
    fontSize: '10px',
    letterSpacing: '0.12em',
    color: '#8b8574',
    marginTop: '8px',
    fontWeight: '600',
    textAlign: 'center',
    minHeight: '14px',
  },
  bigScoreTapZone: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '50%',
    background: 'transparent',
    border: 'none',
    padding: 0,
    cursor: 'pointer',
    zIndex: 2,
  },
  statsSection: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    marginBottom: '24px',
    overflow: 'hidden',
  },
  statRow: {
    padding: '14px 16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottom: '1px solid #f0ead9',
    gap: '12px',
  },
  statRowLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    fontSize: '13px',
    color: '#3a3a3a',
    fontWeight: '500',
    whiteSpace: 'nowrap',
    flexShrink: 0,
    minWidth: '60px',
  },
  autoBadge: {
    fontSize: '9px',
    letterSpacing: '0.15em',
    color: '#1f5e3a',
    background: '#e8f0e3',
    padding: '2px 6px',
    borderRadius: '2px',
    fontWeight: '700',
  },
  miniStepper: {
    display: 'flex',
    alignItems: 'center',
    background: '#faf6ee',
    border: '1px solid #d4ccbb',
    borderRadius: '4px',
    overflow: 'hidden',
    height: '34px',
  },
  miniStepperTapZone: {
    width: '36px',
    height: '100%',
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#1f3d2e',
    padding: 0,
  },
  miniStepperValue: {
    minWidth: '32px',
    fontSize: '15px',
    fontWeight: '800',
    color: '#1f3d2e',
    textAlign: 'center',
    lineHeight: 1,
    borderLeft: '1px solid #d4ccbb',
    borderRight: '1px solid #d4ccbb',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#fff',
  },
  penaltyGroup: {
    display: 'flex',
    gap: '8px',
    flex: 1,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  penaltyItem: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
  },
  penaltyStepper: {
    display: 'flex',
    alignItems: 'center',
    background: '#faf6ee',
    border: '1px solid #d4ccbb',
    borderRadius: '4px',
    overflow: 'hidden',
    height: '34px',
    width: '100%',
  },
  penaltyStepperTapZone: {
    flex: 1,
    height: '100%',
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#1f3d2e',
    padding: 0,
    cursor: 'pointer',
  },
  penaltyStepperValue: {
    minWidth: '40px',
    fontSize: '15px',
    fontWeight: '800',
    color: '#1f3d2e',
    textAlign: 'center',
    lineHeight: 1,
    borderLeft: '1px solid #d4ccbb',
    borderRight: '1px solid #d4ccbb',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#fff',
    padding: '0 12px',
  },
  penaltyLabel: {
    fontSize: '12px',
    letterSpacing: '0.1em',
    color: '#8b8574',
    fontWeight: '700',
    textAlign: 'center',
    margin: '0',
  },
  penaltyBadge: {
    fontSize: '12px',
    letterSpacing: '0.05em',
    color: '#fff',
    background: '#c04a3e',
    padding: '2px 7px',
    borderRadius: '8px',
    fontWeight: '800',
  },
  penaltyTotalBadge: {
    fontSize: '12px',
    fontWeight: '800',
    color: '#c04a3e',
    background: '#ffe8e3',
    padding: '6px 10px',
    borderRadius: '3px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '44px',
    textAlign: 'center',
  },
  toggleRow: {
    display: 'flex',
    gap: '3px',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  toggleBtn: {
    padding: '5px 8px',
    borderRadius: '2px',
    border: '1px solid #d4ccbb',
    fontSize: '10px',
    fontWeight: '600',
    display: 'flex',
    alignItems: 'center',
    gap: '3px',
    minHeight: '30px',
    minWidth: '0',
    whiteSpace: 'nowrap',
  },

  // ===== ?쇳똿 + 硫붾え 遺꾪븷 ??(3:1) =====
  puttMemoRow: {
    display: 'flex',
    width: '260px',
    gap: '8px',
    alignItems: 'center',
    flexShrink: 0,
  },
  // ===== Split Stepper (PAR ?ㅼ젙 ?ㅽ??쇨낵 ?숈씪??醫???遺꾪븷 ?? =====
  splitStepper: {
    position: 'relative',
    background: '#faf6ee',
    border: '1px solid #d4ccbb',
    borderRadius: '4px',
    overflow: 'hidden',
    height: '34px',
    userSelect: 'none',
  },
  splitStepperHalves: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    pointerEvents: 'none',
  },
  splitStepperLeftHalf: {
    flex: 1,
    background: 'rgba(31, 61, 46, 0.02)',
  },
  splitStepperRightHalf: {
    flex: 1,
    background: 'rgba(31, 61, 46, 0.18)',
  },
  splitStepperContent: {
    position: 'relative',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'none',
    zIndex: 1,
  },
  splitStepperValue: {
    fontSize: '15px',
    fontWeight: '800',
    color: '#1f3d2e',
    lineHeight: 1,
    minWidth: '24px',
    textAlign: 'center',
  },
  splitStepperSideIcon: {
    position: 'absolute',
    top: '50%',
    transform: 'translateY(-50%)',
    color: '#5e7d6a',
    pointerEvents: 'none',
    zIndex: 1,
    display: 'flex',
    alignItems: 'center',
  },
  splitStepperTapZone: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    width: '50%',
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    zIndex: 2,
  },
  puttStepper: {
    flex: 3,
    display: 'flex',
    alignItems: 'center',
    background: '#faf6ee',
    border: '1px solid #d4ccbb',
    borderRadius: '4px',
    overflow: 'hidden',
    height: '34px',
  },
  puttStepperTapZone: {
    flex: 1,
    height: '100%',
    background: 'transparent',
    border: 'none',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#1f3d2e',
    padding: 0,
    cursor: 'pointer',
  },
  puttStepperValue: {
    minWidth: '40px',
    fontSize: '15px',
    fontWeight: '800',
    color: '#1f3d2e',
    textAlign: 'center',
    lineHeight: 1,
    borderLeft: '1px solid #d4ccbb',
    borderRight: '1px solid #d4ccbb',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: '#fff',
    padding: '0 12px',
  },
  memoButton: {
    flex: 1,
    height: '34px',
    padding: '0 6px',
    background: 'transparent',
    border: '1.5px solid #d4ccbb',
    borderRadius: '4px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    fontSize: '12px',
    fontWeight: '700',
    color: '#3a3a3a',
    cursor: 'pointer',
    position: 'relative',
    transition: 'all 0.15s ease',
  },
  memoButtonFilled: {
    background: '#1f3d2e',
    borderColor: '#1f3d2e',
    color: '#f5f0e6',
  },
  memoDot: {
    position: 'absolute',
    top: '4px',
    right: '6px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: '#d9a441',
  },

  // ===== 硫붾え 紐⑤떖 =====
  memoModalCard: {
    background: '#fff',
    borderRadius: '8px',
    padding: '24px 22px 20px',
    width: '100%',
    maxWidth: '420px',
    boxShadow: '0 12px 40px rgba(0,0,0,0.2)',
    animation: 'modalSlideUp 0.25s ease-out',
  },
  memoModalHeader: {
    marginBottom: '14px',
    textAlign: 'center',
  },
  memoModalTitle: {
    fontSize: '18px',
    fontWeight: '800',
    color: '#1f3d2e',
    letterSpacing: '-0.01em',
    marginBottom: '4px',
  },
  memoModalSub: {
    fontSize: '11px',
    color: '#8b8574',
    fontWeight: '600',
  },
  memoTextarea: {
    width: '100%',
    minHeight: '160px',
    padding: '12px 14px',
    fontSize: '14px',
    fontFamily: "'Noto Sans KR', sans-serif",
    color: '#1f3d2e',
    border: '1.5px solid #d4ccbb',
    borderRadius: '4px',
    background: '#faf6ee',
    resize: 'vertical',
    outline: 'none',
    lineHeight: 1.5,
  },
  memoCharCount: {
    fontSize: '11px',
    color: '#8b8574',
    textAlign: 'right',
    marginTop: '6px',
    marginBottom: '14px',
    fontWeight: '600',
  },
  memoSaveBtn: {
    flex: 1,
    padding: '14px',
    background: '#1f3d2e',
    color: '#fff',
    fontSize: '13px',
    fontWeight: '700',
    borderRadius: '4px',
    letterSpacing: '0.02em',
  },

  // ===== 遺꾩꽍 酉?- ?명듃 移대뱶 =====
  notesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  noteCard: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderLeft: '3px solid #d9a441',
    borderRadius: '3px',
    padding: '14px 16px',
  },
  noteCardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
    gap: '8px',
  },
  noteCardHole: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
    fontSize: '13px',
    fontWeight: '800',
    color: '#1f3d2e',
    letterSpacing: '0.02em',
  },
  noteCardPar: {
    fontSize: '10px',
    color: '#8b8574',
    fontWeight: '600',
  },
  noteCardScore: {
    fontSize: '13px',
    fontWeight: '800',
  },
  noteCardBody: {
    fontSize: '13px',
    color: '#3a3a3a',
    lineHeight: 1.6,
    whiteSpace: 'pre-wrap',
    wordBreak: 'break-word',
  },
  shotShapeSection: {
    padding: '14px 16px',
    borderBottom: '1px solid #f0ead9',
  },
  shotShapeSectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontSize: '13px',
    color: '#3a3a3a',
    fontWeight: '500',
    marginBottom: '10px',
  },
  shotShapeMatrixHeader: {
    display: 'flex',
    fontSize: '9px',
    color: '#8b8574',
    fontWeight: '700',
    letterSpacing: '0.05em',
    marginBottom: '6px',
    padding: '0 4px',
  },
  shotShapeMatrixCenter: {
    flex: 1,
    textAlign: 'center',
  },
  shotShapeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: '5px',
  },
  shotShapeCell: {
    minHeight: '78px',
    padding: '6px 2px',
    borderRadius: '4px',
    border: '1.5px solid',
    fontWeight: '700',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '2px',
    transition: 'all 0.15s ease',
    cursor: 'pointer',
    background: 'transparent',
  },
  shotShapeCellLabel: {
    fontSize: '10px',
    fontWeight: '700',
    letterSpacing: '0.01em',
    lineHeight: 1.1,
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  shotShapeRow: {
    display: 'flex',
    gap: '3px',
    flex: 1,
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  shotShapeBtn: {
    flex: 1,
    minWidth: '32px',
    height: '32px',
    padding: '2px 2px',
    borderRadius: '3px',
    border: '1.5px solid',
    fontWeight: '700',
    fontSize: '12px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.15s ease',
    cursor: 'pointer',
    background: 'transparent',
  },
  shotShapeLabel: {
    fontSize: '10px',
    fontWeight: '700',
    letterSpacing: '-0.02em',
    lineHeight: 1,
    whiteSpace: 'nowrap',
  },
  fairwayHitRow: {
    display: 'flex',
    gap: '3px',
    flex: 1,
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  fairwayHitBtn: {
    flex: 1,
    minWidth: '34px',
    height: '32px',
    borderRadius: '3px',
    border: '1.5px solid',
    fontSize: '12px',
    fontWeight: '800',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    letterSpacing: '0.05em',
    cursor: 'pointer',
    transition: 'all 0.15s ease',
    padding: '2px',
  },
  scoringNav: {
    display: 'flex',
    gap: '10px',
    marginTop: '20px',
  },
  navBtn: {
    flex: 1,
    padding: '14px',
    background: 'transparent',
    border: '1px solid #1f3d2e',
    color: '#1f3d2e',
    fontSize: '13px',
    fontWeight: '600',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    borderRadius: '2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '6px',
  },
  finishBtn: {
    flex: 1,
    padding: '14px',
    background: '#1f3d2e',
    color: '#f5f0e6',
    fontSize: '13px',
    fontWeight: '600',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    borderRadius: '2px',
  },
  reportHero: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    padding: '28px 24px',
    marginBottom: '24px',
    textAlign: 'center',
  },
  reportDate: {
    fontSize: '11px',
    letterSpacing: '0.2em',
    color: '#8b8574',
    textTransform: 'uppercase',
    marginBottom: '8px',
  },
  reportCourse: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '22px',
    fontWeight: '700',
    color: '#1f3d2e',
    margin: '0 0 20px',
  },
  bigScoreDisplay: {
    padding: '16px 0',
  },
  bigScoreNum: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '64px',
    fontWeight: '800',
    color: '#1f3d2e',
    lineHeight: 1,
    letterSpacing: '-0.02em',
  },
  bigScoreDiff: {
    fontSize: '18px',
    fontWeight: '600',
    marginTop: '4px',
  },
  bigScoreLabel: {
    fontSize: '11px',
    color: '#8b8574',
    letterSpacing: '0.15em',
    marginTop: '6px',
  },
  nineGrid: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '40px',
    marginTop: '20px',
    paddingTop: '20px',
    borderTop: '1px solid #ebe4d3',
  },
  nineItem: {
    textAlign: 'center',
  },
  nineDivider: {
    width: '1px',
    height: '40px',
    background: '#ebe4d3',
  },
  nineLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: '#8b8574',
    fontWeight: '600',
    marginBottom: '4px',
  },
  nineValue: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '22px',
    fontWeight: '800',
    color: '#1f3d2e',
    letterSpacing: '-0.02em',
  },
  keyStatsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '8px',
  },
  statTile: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    padding: '16px 14px',
    textAlign: 'center',
  },
  tileLabel: {
    fontSize: '10px',
    letterSpacing: '0.2em',
    color: '#8b8574',
    textTransform: 'uppercase',
    marginBottom: '6px',
    fontWeight: '600',
  },
  tileValue: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '28px',
    fontWeight: '700',
    color: '#1f3d2e',
    lineHeight: 1,
  },
  tileSub: {
    fontSize: '11px',
    color: '#8b8574',
    marginTop: '6px',
  },
  breakdownList: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    padding: '16px',
  },
  breakdownRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '8px 0',
  },
  breakdownLabel: {
    width: '70px',
    fontSize: '12px',
    color: '#3a3a3a',
    fontWeight: '500',
  },
  breakdownBarTrack: {
    flex: 1,
    height: '6px',
    background: '#f0ead9',
    borderRadius: '3px',
    overflow: 'hidden',
  },
  breakdownBarFill: {
    height: '100%',
    borderRadius: '3px',
    transition: 'width 0.4s ease-out',
  },
  breakdownCount: {
    width: '24px',
    textAlign: 'right',
    fontSize: '13px',
    fontWeight: '600',
    color: '#1f3d2e',
  },
  scorecardWrap: {
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  scorecardTable: {
    background: '#fff',
    border: '1px solid #d4ccbb',
    borderRadius: '4px',
    overflow: 'hidden',
  },
  scorecardTableRow: {
    display: 'flex',
    alignItems: 'stretch',
    borderBottom: '1px solid #ebe4d3',
    minHeight: '30px',
  },
  scorecardRowLabel: {
    width: '46px',
    flexShrink: 0,
    background: '#f5f0e6',
    borderRight: '1px solid #d4ccbb',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '10px',
    letterSpacing: '0.1em',
    fontWeight: '700',
    color: '#6b6558',
  },
  scorecardRowLabelHeader: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    fontSize: '11px',
    letterSpacing: '0.15em',
  },
  scorecardTableCells: {
    display: 'grid',
    gridTemplateColumns: 'repeat(9, 1fr)',
    flex: 1,
    minWidth: 0,
  },
  scorecardHeaderCell: {
    padding: '6px 0',
    fontSize: '12px',
    fontWeight: '700',
    color: '#3a3a3a',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: '1px solid #ebe4d3',
    minWidth: 0,
  },
  scorecardParCell: {
    padding: '5px 0',
    fontSize: '12px',
    fontWeight: '600',
    color: '#6b6558',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: '1px solid #ebe4d3',
    minWidth: 0,
  },
  scorecardScoreCell: {
    padding: '3px 2px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: '1px solid #ebe4d3',
    minWidth: 0,
  },
  scorecardPuttCell: {
    padding: '5px 0',
    fontSize: '11px',
    fontWeight: '600',
    color: '#8b8574',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRight: '1px solid #ebe4d3',
    minWidth: 0,
  },
  scorecardTotalCell: {
    width: '58px',
    flexShrink: 0,
    background: '#f5f0e6',
    borderLeft: '1.5px solid #d4ccbb',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: '700',
    color: '#1f3d2e',
    gap: '3px',
  },
  scorecardTotalHeader: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    fontSize: '10px',
    letterSpacing: '0.15em',
  },
  scorecardTotalDiff: {
    fontSize: '10px',
    fontWeight: '600',
    opacity: 0.75,
  },
  scorecardGrandTotal: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    borderRadius: '4px',
    padding: '14px 16px',
    textAlign: 'center',
  },
  scorecardGrandRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  scorecardGrandLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: '#a8c2a5',
    fontWeight: '700',
  },
  scorecardGrandValues: {
    display: 'flex',
    justifyContent: 'space-around',
    alignItems: 'center',
    gap: '8px',
  },
  scorecardGrandItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
  },
  scorecardGrandItemLabel: {
    fontSize: '9px',
    letterSpacing: '0.15em',
    color: '#a8c2a5',
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  scorecardGrandItemValue: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '20px',
    fontWeight: '700',
    color: '#f5f0e6',
    lineHeight: 1,
  },
  insightsList: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    padding: '6px 0',
  },
  insightRow: {
    display: 'flex',
    gap: '12px',
    padding: '14px 16px',
    borderBottom: '1px solid #f0ead9',
    alignItems: 'flex-start',
  },
  insightIcon: {
    fontSize: '18px',
  },
  insightText: {
    flex: 1,
    fontSize: '13px',
    lineHeight: 1.5,
    color: '#3a3a3a',
  },
  historyList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  historyCard: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    display: 'flex',
    alignItems: 'stretch',
  },
  historyCardMain: {
    flex: 1,
    padding: '16px 18px',
    background: 'transparent',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    textAlign: 'left',
  },
  historyCardLeft: {
    flex: 1,
  },
  historyCourse: {
    fontSize: '15px',
    fontWeight: '600',
    color: '#1f3d2e',
    marginBottom: '4px',
  },
  historyMeta: {
    fontSize: '12px',
    color: '#8b8574',
  },
  historyCardRight: {
    textAlign: 'right',
    marginLeft: '16px',
  },
  historyScore: {
    fontFamily: "'Noto Sans KR', sans-serif",
    fontSize: '24px',
    fontWeight: '800',
    color: '#1f3d2e',
    lineHeight: 1,
    letterSpacing: '-0.02em',
  },
  historyDiff: {
    fontSize: '12px',
    fontWeight: '600',
    marginTop: '2px',
  },
  deleteBtn: {
    padding: '0 16px',
    background: 'transparent',
    borderLeft: '1px solid #ebe4d3',
    color: '#c04a3e',
    display: 'flex',
    alignItems: 'center',
  },
  emptyState: {
    textAlign: 'center',
    padding: '60px 20px',
  },
  emptyIcon: {
    fontSize: '48px',
    marginBottom: '16px',
  },
  emptyTitle: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#1f3d2e',
    marginBottom: '6px',
  },
  emptySub: {
    fontSize: '13px',
    color: '#8b8574',
  },
  trendChart: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    padding: '16px',
    display: 'flex',
    alignItems: 'flex-end',
    gap: '8px',
    height: '180px',
    overflowX: 'auto',
  },
  trendCol: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    minWidth: '40px',
    height: '100%',
    position: 'relative',
  },
  trendValue: {
    fontSize: '11px',
    fontWeight: '600',
    color: '#1f3d2e',
    marginBottom: '4px',
  },
  trendBar: {
    width: '18px',
    background: '#1f3d2e',
    borderRadius: '2px 2px 0 0',
    minHeight: '8px',
  },
  trendDate: {
    fontSize: '9px',
    color: '#8b8574',
    marginTop: '6px',
    textAlign: 'center',
  },

  // ===== BOTTOM TAB BAR =====
  tabBar: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    background: '#ffffff',
    borderTop: '1px solid #e4ddcc',
    boxShadow: '0 -2px 12px rgba(31, 61, 46, 0.06)',
    zIndex: 100,
    paddingBottom: 'env(safe-area-inset-bottom, 0)',
  },
  tabBarInner: {
    maxWidth: '520px',
    margin: '0 auto',
    display: 'grid',
    gridTemplateColumns: 'repeat(5, 1fr)',
  },
  tabBarBtn: {
    background: 'transparent',
    border: 'none',
    padding: '10px 2px 12px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '4px',
    position: 'relative',
    cursor: 'pointer',
    transition: 'color 0.15s ease',
    minHeight: '56px',
  },
  tabBarBtnHome: {
    padding: '6px 2px 12px',
  },
  tabBarLabel: {
    fontSize: '9px',
    letterSpacing: '0.03em',
    lineHeight: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    maxWidth: '100%',
  },
  tabBarActiveIndicator: {
    position: 'absolute',
    top: 0,
    left: '50%',
    transform: 'translateX(-50%)',
    width: '28px',
    height: '3px',
    background: '#1f3d2e',
    borderRadius: '0 0 3px 3px',
  },

  // ===== INSIGHTS =====
  insightsBanner: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    borderRadius: '4px',
    padding: '18px 20px',
    marginBottom: '24px',
    textAlign: 'center',
  },
  insightsBannerLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: '#a8c2a5',
    fontWeight: '700',
    marginBottom: '8px',
  },
  insightsBannerValue: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'center',
    gap: '4px',
    fontSize: '28px',
    fontWeight: '800',
    letterSpacing: '-0.02em',
  },
  insightsBannerSub: {
    fontSize: '11px',
    fontWeight: '600',
    color: '#a8c2a5',
    letterSpacing: '0.1em',
  },
  insightsBannerDot: {
    color: '#4a5e51',
    margin: '0 8px',
    fontSize: '20px',
  },

  // Style Card
  styleCard: {
    background: '#fff',
    border: '2px solid',
    borderRadius: '6px',
    padding: '20px',
    display: 'flex',
    gap: '16px',
    alignItems: 'flex-start',
    marginBottom: '10px',
  },
  styleIconWrap: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    background: '#f5f0e6',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  styleIconEmoji: {
    fontSize: '30px',
    lineHeight: 1,
  },
  styleContent: {
    flex: 1,
    minWidth: 0,
  },
  styleType: {
    fontSize: '15px',
    fontWeight: '800',
    letterSpacing: '-0.01em',
    marginBottom: '4px',
    lineHeight: 1.2,
  },
  styleSubtitle: {
    fontSize: '12px',
    color: '#6b6558',
    fontWeight: '600',
    marginBottom: '10px',
    lineHeight: 1.4,
  },
  styleDescription: {
    fontSize: '12px',
    color: '#3a3a3a',
    lineHeight: 1.6,
  },
  styleMetrics: {
    display: 'flex',
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    padding: '12px 4px',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  styleMetric: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '4px',
    padding: '0 4px',
    minWidth: 0,
  },
  styleMetricLabel: {
    fontSize: '9px',
    letterSpacing: '0.1em',
    color: '#8b8574',
    fontWeight: '700',
    textAlign: 'center',
  },
  styleMetricValue: {
    fontSize: '18px',
    fontWeight: '800',
    color: '#1f3d2e',
    letterSpacing: '-0.02em',
    lineHeight: 1,
  },
  styleMetricDivider: {
    width: '1px',
    height: '28px',
    background: '#ebe4d3',
    flexShrink: 0,
  },
  insightCards: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  insightCard: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderLeft: '3px solid',
    borderRadius: '3px',
    padding: '14px 16px',
    display: 'flex',
    alignItems: 'flex-start',
    gap: '12px',
  },
  insightCardBadge: {
    width: '28px',
    height: '28px',
    borderRadius: '50%',
    background: '#e8f0e3',
    color: '#1f5e3a',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '800',
    fontSize: '14px',
    flexShrink: 0,
  },
  insightCardContent: {
    flex: 1,
  },
  insightCardTitle: {
    fontSize: '14px',
    fontWeight: '700',
    color: '#1f3d2e',
    marginBottom: '4px',
  },
  insightCardDetail: {
    fontSize: '12px',
    color: '#6b6558',
    lineHeight: 1.5,
  },
  parAnalysis: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    overflow: 'hidden',
  },
  parAnalysisRow: {
    display: 'flex',
    alignItems: 'center',
    padding: '14px 16px',
    borderBottom: '1px solid #f0ead9',
    gap: '14px',
  },
  parAnalysisBadge: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    padding: '6px 10px',
    borderRadius: '2px',
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '0.08em',
    minWidth: '52px',
    textAlign: 'center',
  },
  parAnalysisData: {
    flex: 1,
  },
  parAnalysisMain: {
    display: 'flex',
    alignItems: 'baseline',
    gap: '8px',
  },
  parAnalysisStrokes: {
    fontSize: '20px',
    fontWeight: '800',
    color: '#1f3d2e',
    letterSpacing: '-0.02em',
  },
  parAnalysisDiff: {
    fontSize: '13px',
    fontWeight: '700',
  },
  parAnalysisCount: {
    fontSize: '11px',
    color: '#8b8574',
    marginLeft: 'auto',
  },
  parAnalysisRates: {
    fontSize: '11px',
    color: '#6b6558',
    marginTop: '4px',
  },
  parAnalysisDot: {
    color: '#c8c0b0',
    margin: '0 6px',
  },
  paceCard: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    padding: '18px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '10px',
  },
  paceRow: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '6px',
    flex: 1,
  },
  paceLabel: {
    fontSize: '10px',
    letterSpacing: '0.2em',
    color: '#8b8574',
    fontWeight: '700',
  },
  paceValue: {
    fontSize: '24px',
    fontWeight: '800',
    color: '#1f3d2e',
    letterSpacing: '-0.02em',
  },
  paceSub: {
    fontSize: '10px',
    color: '#8b8574',
    fontWeight: '500',
    marginLeft: '3px',
  },
  paceArrow: {
    fontSize: '28px',
    color: '#1f5e3a',
    fontWeight: '300',
    padding: '0 14px',
  },
  paceInsight: {
    padding: '12px 14px',
    background: '#f5f0e6',
    borderRadius: '3px',
    fontSize: '12px',
    color: '#3a3a3a',
    lineHeight: 1.5,
    textAlign: 'center',
  },

  // ===== MY BAG =====
  bagBanner: {
    background: '#1f3d2e',
    color: '#f5f0e6',
    borderRadius: '4px',
    padding: '18px 20px',
    marginBottom: '16px',
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  bagBannerIcon: {
    fontSize: '32px',
  },
  bagBannerLabel: {
    fontSize: '10px',
    letterSpacing: '0.25em',
    color: '#a8c2a5',
    fontWeight: '700',
    marginBottom: '4px',
  },
  bagBannerValue: {
    fontSize: '26px',
    fontWeight: '800',
    letterSpacing: '-0.02em',
  },
  bagBannerSub: {
    fontSize: '11px',
    color: '#a8c2a5',
    fontWeight: '600',
    letterSpacing: '0.08em',
  },
  bagHint: {
    fontSize: '11px',
    color: '#8b8574',
    textAlign: 'center',
    marginBottom: '20px',
    fontStyle: 'italic',
  },
  // ===== CLUB CARD =====
  clubList: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    overflow: 'hidden',
  },
  clubCard: {
    padding: '14px 16px',
    borderBottom: '1px solid #f0ead9',
  },
  clubCardHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '10px',
  },
  clubName: {
    fontSize: '15px',
    fontWeight: '800',
    color: '#1f3d2e',
    letterSpacing: '-0.01em',
  },
  clubRunBadge: {
    background: '#f5f0e6',
    color: '#8b6f47',
    border: '1px solid #e0d6bc',
    padding: '3px 8px',
    borderRadius: '2px',
    fontSize: '10px',
    fontWeight: '700',
    letterSpacing: '0.03em',
  },
  clubFieldRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '6px 0',
    gap: '12px',
  },
  clubFieldLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1px',
    minWidth: 0,
  },
  clubFieldLabelMain: {
    fontSize: '13px',
    fontWeight: '700',
    color: '#3a3a3a',
  },
  clubFieldLabelSub: {
    fontSize: '9px',
    letterSpacing: '0.12em',
    color: '#8b8574',
    fontWeight: '600',
  },
  clubStepper: {
    display: 'flex',
    alignItems: 'center',
    background: '#faf6ee',
    border: '1px solid #d4ccbb',
    borderRadius: '4px',
    overflow: 'hidden',
    height: '34px',
    flexShrink: 0,
  },
  clubStepperHighlight: {
    borderColor: '#1f3d2e',
    background: '#e8f0e3',
  },
  clubStepperValue: {
    minWidth: '80px',
    fontSize: '13px',
    fontWeight: '700',
    color: '#1f3d2e',
    textAlign: 'center',
    lineHeight: 1,
    borderLeft: '1px solid #d4ccbb',
    borderRight: '1px solid #d4ccbb',
    height: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '3px',
    background: '#fff',
    padding: '0 8px',
  },
  clubAvgNum: {
    fontSize: '15px',
    fontWeight: '800',
    letterSpacing: '-0.02em',
  },
  clubAvgUnit: {
    fontSize: '10px',
    fontWeight: '600',
    color: '#8b8574',
    letterSpacing: '0.05em',
  },

  // ===== DISTANCE CHART (DUAL BAR) =====
  distanceChartLegend: {
    display: 'flex',
    justifyContent: 'center',
    gap: '20px',
    marginBottom: '10px',
    fontSize: '11px',
    color: '#6b6558',
    fontWeight: '600',
  },
  distanceLegendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
  },
  distanceLegendDot: {
    width: '10px',
    height: '10px',
    borderRadius: '2px',
  },
  distanceChart: {
    background: '#fff',
    border: '1px solid #ebe4d3',
    borderRadius: '3px',
    padding: '14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
  },
  distanceRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  distanceLabel: {
    width: '62px',
    fontSize: '12px',
    fontWeight: '700',
    color: '#3a3a3a',
    flexShrink: 0,
  },
  distanceBarTrack: {
    flex: 1,
    height: '18px',
    background: '#f0ead9',
    borderRadius: '3px',
    overflow: 'hidden',
    position: 'relative',
  },
  distanceBarFillTotal: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    background: '#1f3d2e',
    borderRadius: '3px',
    transition: 'width 0.4s ease',
  },
  distanceBarFillCarry: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    background: '#a8c2a5',
    borderRadius: '3px',
    transition: 'width 0.4s ease',
    zIndex: 1,
  },
  distanceValues: {
    width: '68px',
    textAlign: 'right',
    flexShrink: 0,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '0',
    lineHeight: 1.1,
  },
  distanceValueCarry: {
    fontSize: '10px',
    fontWeight: '600',
    color: '#5e8a5f',
  },
  distanceValueTotal: {
    fontSize: '13px',
    fontWeight: '800',
    color: '#1f3d2e',
    letterSpacing: '-0.02em',
  },

  // ===== MODAL =====
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(31, 61, 46, 0.5)',
    backdropFilter: 'blur(4px)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '20px',
    zIndex: 1000,
    animation: 'modalFadeIn 0.2s ease-out',
  },
  modalCard: {
    background: '#fff',
    borderRadius: '8px',
    padding: '28px 24px 20px',
    width: '100%',
    maxWidth: '340px',
    textAlign: 'center',
    boxShadow: '0 12px 40px rgba(0,0,0,0.2)',
    animation: 'modalSlideUp 0.25s ease-out',
  },
  modalIcon: {
    fontSize: '40px',
    marginBottom: '8px',
  },
  modalTitle: {
    fontSize: '17px',
    fontWeight: '800',
    color: '#1f3d2e',
    marginBottom: '8px',
    letterSpacing: '-0.01em',
  },
  modalText: {
    fontSize: '13px',
    color: '#6b6558',
    lineHeight: 1.5,
    marginBottom: '20px',
  },
  modalActions: {
    display: 'flex',
    gap: '8px',
  },
  modalBtnCancel: {
    flex: 1,
    padding: '14px',
    background: '#f5f0e6',
    color: '#1f3d2e',
    fontSize: '13px',
    fontWeight: '700',
    borderRadius: '4px',
    letterSpacing: '0.02em',
  },
  modalBtnConfirm: {
    flex: 1,
    padding: '14px',
    background: '#c04a3e',
    color: '#fff',
    fontSize: '13px',
    fontWeight: '700',
    borderRadius: '4px',
    letterSpacing: '0.02em',
  },
};

export default styles;
